In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("Fact_Used_Cars_Cleaned.csv")

df.head()

,Car_Brand,Vehicle_name,Car_Model,Year_of_Manufacture,Vehicle_Age,Insurance,Fuel_Type,Seats_Capacity,Kms_Driven,RTO,Ownership,Engine_Displacement,Transmission,Power_Bhp,Drive_Type,Mileage_WRT_Fuel,New_Vehicle_Price_Lakh,Vehicle_Price_Lakh,depreciation(%),Other_Features
0,Toyota,Etios,NaN,2013,12,Expired,Diesel,5,150000,Sri Ganganagar,Fourth Owner,1364.0,Manual,NaN,NaN,NaN,8.05,2.60,67.70,NaN
1,Toyota,Glanza,NaN,2024,1,Expired,Petrol,5,10000,dasuya,First Owner,1197.0,Manual,NaN,NaN,NaN,11.28,9.40,16.67,NaN
2,Hyundai,Creta,1.4 E,2017,8,Comprehensive,Diesel,5,75000,Gurgaon,First Owner,1396.0,Manual,NaN,NaN,NaN,11.86,6.25,47.30,NaN
3,Volkswagen,Vento,Diesel,2011,14,Expired,Diesel,5,160000,jalalabad,Third Owner,1598.0,Manual,103.6,NaN,20.54,10.05,1.40,86.07,['Parking Sensors']
4,Hyundai,Verna,1.6,2014,11,Expired,Diesel,5,120000,Meerut,First Owner,1582.0,Manual,126.3,NaN,22.32,11.87,4.00,66.30,"['Automatic Climate Control', 'Parking Sensors']"

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10224 entries, 0 to 10223
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Car_Brand               10224 non-null  str
 1   Vehicle_name            10224 non-null  str
 2   Car_Model               8605 non-null   str
 3   Year_of_Manufacture     10224 non-null  int64
 4   Vehicle_Age             10224 non-null  int64
 5   Insurance               10224 non-null  str
 6   Fuel_Type               10224 non-null  str
 7   Seats_Capacity          10224 non-null  int64
 8   Kms_Driven              10224 non-null  int64
 9   RTO                     10224 non-null  str
 10  Ownership               10221 non-null  str
 11  Engine_Displacement     10142 non-null  float64
 12  Transmission            10224 non-null  str
 13  Power_Bhp               7098 non-null   float64
 14  Drive_Type              2247 non-null   str
 15  Mileage_WRT_Fuel        6809 non-null   float64
 16  New_Vehicle_Price_Lakh  10224 non-null  float64
 17  Vehicle_Price_Lakh      10224 non-null  float64
 18  depreciation(%)         10224 non-null  float64
 19  Other_Features          6378 non-null   str
dtypes: float64(6), int64(4), str(10)
memory usage: 2.6 MB

In [3]:
df.columns

Index(['Car_Brand', 'Vehicle_name', 'Car_Model', 'Year_of_Manufacture',
       'Vehicle_Age', 'Insurance', 'Fuel_Type', 'Seats_Capacity', 'Kms_Driven',
       'RTO', 'Ownership', 'Engine_Displacement', 'Transmission', 'Power_Bhp',
       'Drive_Type', 'Mileage_WRT_Fuel', 'New_Vehicle_Price_Lakh',
       'Vehicle_Price_Lakh', 'depreciation(%)', 'Other_Features'],
      dtype='str')

In [4]:
df["Car_Brand"].isnull().sum()

np.int64(0)

In [5]:
df["Car_Brand"].nunique()

36

In [6]:
df["Car_Brand"].unique()

<ArrowStringArray>
[       'Toyota',       'Hyundai',    'Volkswagen',          'Tata',
      'Mahindra',        'Maruti',         'Skoda',         'Honda',
          'Ford',     'Chevrolet',        'Datsun',           'Kia',
          'Audi',            'MG',         'Force', 'Mercedes-Benz',
       'Renault',        'Nissan',          'Jeep',    'Land Rover',
         'Volvo',        'Jaguar',           'BMW',          'Mini',
          'Fiat',    'Mitsubishi',         'Isuzu',         'Lexus',
       'Porsche',           'BYD',       'Citroen',         'Ashok',
       'Bentley',       'Ferrari',   'Lamborghini',    'Ambassador']
Length: 36, dtype: str

In [7]:
dim_brand = (
    df[["Car_Brand"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

dim_brand["Brand_ID"] = dim_brand.index + 1

dim_brand = dim_brand[["Brand_ID", "Car_Brand"]]

dim_brand.head()

   Brand_ID   Car_Brand
0         1      Toyota
1         2     Hyundai
2         3  Volkswagen
3         4        Tata
4         5    Mahindra

In [8]:
dim_brand.shape

(36, 2)

In [9]:
dim_brand["Car_Brand"].duplicated().sum()

np.int64(0)

In [10]:
dim_brand.to_csv(
    "Used_Car_Analytics_Output/Dim_Brand.csv",
    index=False
)

In [11]:
df["Car_Model"].isnull().sum()

np.int64(1619)

In [12]:
df["Car_Model"].nunique()

1704

In [13]:
df["Car_Model"].drop_duplicates().head(50)

0                         NaN
2                       1.4 E
3                      Diesel
4                         1.6
5                Xing GL Plus
7                     XZ Plus
8                1.5 Revotorq
9                    1.4 CRDi
11                      R W10
12                 Brezza VDi
13                  Dzire ZXI
14                    SLX 2WD
15                   E Diesel
16             Active 2.0 TDI
17           1.5 TDI Ambition
18                   VDi Plus
19           Elegance 1.9 TDI
20                   2.0L TDI
21                          E
22                      Dzire
25                      R LXI
26                        300
27                        S11
29                          S
30                N Z8 Diesel
32                   1.6 CRDi
33                    1.3 AMT
34          Corporate Edition
36                     i VTEC
38                        1.3
39                        1.4
41                 Diesel TRD
42                    1.0 MPI
43                       Liva
44       XZ Plus Dark Edition
46                     SX Opt
47                      1.0 T
48    Vitara Zeta Plus Hybrid
49                Anniversary
53                 2nd Gen VX
55               i10 1.2 CRDi
56                Asta Option
59                         EX
60        1.5 Diesel Titanium
61                     Brezza
64                     i DTEC
70                         VX
71    Brezza ZXI Plus AT Dual
80       ROXX AX7L 4WD Diesel
83        Elegance 2.0 TDI CR
Name: Car_Model, dtype: str

In [14]:
df[df["Car_Model"].isnull()]

,Car_Brand,Vehicle_name,Car_Model,Year_of_Manufacture,Vehicle_Age,Insurance,Fuel_Type,Seats_Capacity,Kms_Driven,RTO,Ownership,Engine_Displacement,Transmission,Power_Bhp,Drive_Type,Mileage_WRT_Fuel,New_Vehicle_Price_Lakh,Vehicle_Price_Lakh,depreciation(%),Other_Features
0,Toyota,Etios,NaN,2013,12,Expired,Diesel,5,150000,Sri Ganganagar,Fourth Owner,1364.0,Manual,NaN,NaN,NaN,8.05,2.60,67.70,NaN
1,Toyota,Glanza,NaN,2024,1,Expired,Petrol,5,10000,dasuya,First Owner,1197.0,Manual,NaN,NaN,NaN,11.28,9.40,16.67,NaN
6,Hyundai,i20,NaN,2023,2,Comprehensive,Petrol,5,9400,HR98,First Owner,1197.0,Manual,NaN,NaN,NaN,8.45,6.85,18.93,NaN
10,Mahindra,Bolero,NaN,2014,11,Expired,Diesel,7,196472,Sri Ganganagar,Third Owner,2523.0,Manual,62.1,RWD,15.96,11.03,5.15,53.31,NaN
23,Maruti,Swift,NaN,2012,13,Third Party,Petrol,5,84476,New Delhi,First Owner,1197.0,Manual,85.8,NaN,18.60,5.77,2.70,53.21,"['Keyless Entry', 'Central Locking', 'Air Cond..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10196,Maruti,Brezza,NaN,2024,1,Expired,Petrol,5,30000,Ludhiana,First Owner,1462.0,Manual,NaN,NaN,NaN,9.95,8.00,19.60,NaN
10202,Maruti,Jimny,NaN,2023,2,Expired,Petrol,4,20000,Dera Bassi,First Owner,1462.0,Manual,103.0,4WD,16.94,15.76,13.50,14.34,"['Automatic Climate Control', 'Cruise Control']"
10215,BMW,X1,NaN,2011,14,Expired,Diesel,5,120000,Chandigarh,Second Owner,1995.0,Automatic,184.0,RWD,NaN,36.50,4.00,89.04,NaN
10217,Maruti,Ciaz,NaN,2015,10,Expired,Petrol,5,80000,Chandigarh,First Owner,1373.0,Manual,NaN,NaN,NaN,8.73,4.00,54.18,NaN
10222,Hyundai,Accent,NaN,2009,16,Expired,Petrol,5,60000,Chandigarh,Second Owner,1495.0,Manual,93.7,NaN,16.36,5.98,0.80,86.62,NaN

In [15]:
df["Car_Model"].isna().sum()

np.int64(1619)

In [16]:
dim_model = (
    df[["Car_Model"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

dim_model["Model_ID"] = dim_model.index + 1

dim_model = dim_model[["Model_ID", "Car_Model"]]

dim_model.head()

   Model_ID     Car_Model
0         1           NaN
1         2         1.4 E
2         3        Diesel
3         4           1.6
4         5  Xing GL Plus

In [17]:
dim_model.shape

(1705, 2)

In [18]:
dim_model["Car_Model"].duplicated().sum()

np.int64(0)

In [19]:
df["Car_Model"].value_counts().head(20)

Car_Model
800             260
Dzire           248
S               143
1.2             115
VXI             101
Brezza           89
Diesel           87
Sportz           86
SX               82
K10              77
R VXI BS         71
R LXI            69
Magna            69
XZ               62
1.3              61
1.2 Revotron     60
i10              57
Dzire VXI        55
VDI              55
Xing             50
Name: count, dtype: int64

In [20]:
dim_model.to_csv(
    "Used_Car_Analytics_Output/Dim_Model.csv",
    index=False
)

In [21]:
dim_model.head(50)

    Model_ID                Car_Model
0          1                      NaN
1          2                    1.4 E
2          3                   Diesel
3          4                      1.6
4          5             Xing GL Plus
5          6                  XZ Plus
6          7             1.5 Revotorq
7          8                 1.4 CRDi
8          9                    R W10
9         10               Brezza VDi
10        11                Dzire ZXI
11        12                  SLX 2WD
12        13                 E Diesel
13        14           Active 2.0 TDI
14        15         1.5 TDI Ambition
15        16                 VDi Plus
16        17         Elegance 1.9 TDI
17        18                 2.0L TDI
18        19                        E
19        20                    Dzire
20        21                    R LXI
21        22                      300
22        23                      S11
23        24                        S
24        25              N Z8 Diesel
25        26                 1.6 CRDi
26        27                  1.3 AMT
27        28        Corporate Edition
28        29                   i VTEC
29        30                      1.3
30        31                      1.4
31        32               Diesel TRD
32        33                  1.0 MPI
33        34                     Liva
34        35     XZ Plus Dark Edition
35        36                   SX Opt
36        37                    1.0 T
37        38  Vitara Zeta Plus Hybrid
38        39              Anniversary
39        40               2nd Gen VX
40        41             i10 1.2 CRDi
41        42              Asta Option
42        43                       EX
43        44      1.5 Diesel Titanium
44        45                   Brezza
45        46                   i DTEC
46        47                       VX
47        48  Brezza ZXI Plus AT Dual
48        49     ROXX AX7L 4WD Diesel
49        50      Elegance 2.0 TDI CR

In [22]:
dim_model.shape

(1705, 2)

In [23]:
dim_model["Car_Model"].duplicated().sum()

np.int64(0)

In [24]:
dim_model["Car_Model"].isnull().sum()

np.int64(1)

In [25]:
dim_model.sample(20)

      Model_ID               Car_Model
1193      1194         AX5 5Str Diesel
120        121                Xing GLS
1267      1268              Accord 2.4
187        188           K10 2010-2014
368        369  1.5 Ti VCT MT Ambiente
1043      1044                 CNG HTR
137        138              Brezza ZXI
53          54         2.2 Titanium AT
621        622          Inscription D5
216        217            2.2 Trend AT
477        478                 E 350 d
943        944              2.8 4WD MT
525        526                 Premium
730        731                     GTX
1280      1281  Platinum (O) Diesel AT
244        245                 1.2 MPI
1352      1353                2.5 VX 7
242        243       1.5 TDCi Ambiente
553        554                 R LX BS
231        232        X AMT VXI Option

In [26]:
dim_model = dim_model.dropna(subset=["Car_Model"]).reset_index(drop=True)

dim_model["Model_ID"] = dim_model.index + 1

dim_model.head()

   Model_ID     Car_Model
0         1         1.4 E
1         2        Diesel
2         3           1.6
3         4  Xing GL Plus
4         5       XZ Plus

In [27]:
dim_model.shape

(1704, 2)

In [28]:
dim_model.to_csv(
    "Used_Car_Analytics_Output/Dim_Model.csv",
    index=False
)

In [29]:
df["Vehicle_name"].isnull().sum()

np.int64(0)

In [30]:
df["Vehicle_name"].nunique()

260

In [31]:
df["Vehicle_name"].drop_duplicates().head(50)

0          Etios
1         Glanza
2          Creta
3          Vento
4          Verna
5         Santro
6            i20
7        Harrier
8          Nexon
10        Bolero
11        XUV500
12        Vitara
13         Swift
16       Octavia
17         Rapid
18          Ciaz
19         Laura
20         Jetta
21       Mobilio
25         Wagon
26           TUV
27       Scorpio
29         Venue
31          Figo
33         Ignis
36          City
38          Sail
42          Ameo
44        Altroz
46         Exter
47        RediGO
48         Grand
49         Amaze
50        Rumion
51         Punch
54          Beat
60      Ecosport
80          Thar
83        Superb
98        Fiesta
100          i10
101            S
104    Endeavour
108        Fabia
114       Innova
116      Alcazar
133          800
135     Fortuner
139        Urban
142        Sonet
Name: Vehicle_name, dtype: str

In [32]:
vehicle_list = (
    df[["Vehicle_name"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

vehicle_list.shape

(260, 1)

In [33]:
vehicle_list.head(50)

   Vehicle_name
0         Etios
1        Glanza
2         Creta
3         Vento
4         Verna
5        Santro
6           i20
7       Harrier
8         Nexon
9        Bolero
10       XUV500
11       Vitara
12        Swift
13      Octavia
14        Rapid
15         Ciaz
16        Laura
17        Jetta
18      Mobilio
19        Wagon
20          TUV
21      Scorpio
22        Venue
23         Figo
24        Ignis
25         City
26         Sail
27         Ameo
28       Altroz
29        Exter
30       RediGO
31        Grand
32        Amaze
33       Rumion
34        Punch
35         Beat
36     Ecosport
37         Thar
38       Superb
39       Fiesta
40          i10
41            S
42    Endeavour
43        Fabia
44       Innova
45      Alcazar
46          800
47     Fortuner
48        Urban
49        Sonet

In [34]:
df["Vehicle_name"].nunique()

260

In [35]:
segment_mapping = {
    "Etios": "Sedan",
    "Glanza": "Hatchback",
    "Creta": "SUV",
    "Vento": "Sedan",
    "Verna": "Sedan",
    "Santro": "Hatchback",
    "i20": "Hatchback",
    "Harrier": "SUV",
    "Nexon": "SUV",
    "Bolero": "SUV",
    "XUV500": "SUV",
    "Vitara": "SUV",
    "Swift": "Hatchback",
    "Octavia": "Sedan",
    "Rapid": "Sedan",
    "Ciaz": "Sedan",
    "Laura": "Sedan",
    "Jetta": "Sedan",
    "Mobilio": "MUV",
    "Wagon": "Hatchback",
    "TUV": "SUV",
    "Scorpio": "SUV",
    "Venue": "SUV",
    "Figo": "Hatchback",
    "Ignis": "Hatchback",
    "City": "Sedan",
    "Sail": "Sedan",
    "Ameo": "Sedan",
    "Altroz": "Hatchback",
    "Exter": "SUV",
    "RediGO": "Hatchback",
    "Grand": "Hatchback",
    "Amaze": "Sedan",
    "Rumion": "MUV",
    "Punch": "SUV",
    "Beat": "Hatchback",
    "Ecosport": "SUV",
    "Thar": "SUV",
    "Superb": "Luxury",
    "Fiesta": "Sedan",
    "i10": "Hatchback",
    "Endeavour": "SUV",
    "Fabia": "Hatchback",
    "Innova": "MUV",
    "Alcazar": "SUV",
    "800": "Hatchback",
    "Fortuner": "SUV",
    "Urban": "SUV",
    "Sonet": "SUV"
}

In [36]:
vehicle_list["Segment"] = vehicle_list["Vehicle_name"].map(segment_mapping)

vehicle_list.head(50)

   Vehicle_name    Segment
0         Etios      Sedan
1        Glanza  Hatchback
2         Creta        SUV
3         Vento      Sedan
4         Verna      Sedan
5        Santro  Hatchback
6           i20  Hatchback
7       Harrier        SUV
8         Nexon        SUV
9        Bolero        SUV
10       XUV500        SUV
11       Vitara        SUV
12        Swift  Hatchback
13      Octavia      Sedan
14        Rapid      Sedan
15         Ciaz      Sedan
16        Laura      Sedan
17        Jetta      Sedan
18      Mobilio        MUV
19        Wagon  Hatchback
20          TUV        SUV
21      Scorpio        SUV
22        Venue        SUV
23         Figo  Hatchback
24        Ignis  Hatchback
25         City      Sedan
26         Sail      Sedan
27         Ameo      Sedan
28       Altroz  Hatchback
29        Exter        SUV
30       RediGO  Hatchback
31        Grand  Hatchback
32        Amaze      Sedan
33       Rumion        MUV
34        Punch        SUV
35         Beat  Hatchback
36     Ecosport        SUV
37         Thar        SUV
38       Superb     Luxury
39       Fiesta      Sedan
40          i10  Hatchback
41            S        NaN
42    Endeavour        SUV
43        Fabia  Hatchback
44       Innova        MUV
45      Alcazar        SUV
46          800  Hatchback
47     Fortuner        SUV
48        Urban        SUV
49        Sonet        SUV

In [37]:
vehicle_list[vehicle_list["Segment"].isnull()]

    Vehicle_name Segment
41             S     NaN
50            Q2     NaN
51        Baleno     NaN
52           EON     NaN
53        Hector     NaN
..           ...     ...
255          e2o     NaN
256  Trailblazer     NaN
257           MU     NaN
258    Outlander     NaN
259        Avigo     NaN

[211 rows x 2 columns]

In [38]:
vehicle_list.tail(50)

    Vehicle_name Segment
210           X4     NaN
211     GL-Class     NaN
212         Sumo     NaN
213        Santa     NaN
214       Taisor     NaN
215      Alturas     NaN
216       Esteem     NaN
217         Kona     NaN
218     Vellfire     NaN
219    Ssangyong     NaN
220     Meridian     NaN
221      Mustang     NaN
222    SLK-Class     NaN
223        Elite     NaN
224           XJ     NaN
225            B     NaN
226       e-tron     NaN
227      Maybach     NaN
228           A5     NaN
229           iX     NaN
230      Captiva     NaN
231          New     NaN
232       BOLERO     NaN
233      Windsor     NaN
234          eC3     NaN
235            A     NaN
236        Kylaq     NaN
237      Invicto     NaN
238           C5     NaN
239       Grande     NaN
240      M-Class     NaN
241          EQB     NaN
242           LX     NaN
243     Bentayga     NaN
244      X-Trail     NaN
245    Avventura     NaN
246     Aircross     NaN
247         Land     NaN
248    CLS-Class     NaN
249         F620     NaN
250     Revuelto     NaN
251           XE     NaN
252      Venture     NaN
253      Kizashi     NaN
254          V40     NaN
255          e2o     NaN
256  Trailblazer     NaN
257           MU     NaN
258    Outlander     NaN
259        Avigo     NaN

In [39]:
additional_segment_mapping = {
    "X4": "SUV",
    "GL-Class": "Luxury",
    "Sumo": "MUV",
    "Santa": "SUV",
    "Taisor": "SUV",
    "Alturas": "SUV",
    "Esteem": "Sedan",
    "Kona": "SUV",
    "Vellfire": "Luxury",
    "Ssangyong": "SUV",
    "Meridian": "SUV",
    "Mustang": "Luxury",
    "SLK-Class": "Luxury",
    "Elite": "Hatchback",
    "XJ": "Luxury",
    "B": "Luxury",
    "e-tron": "EV",
    "Maybach": "Luxury",
    "A5": "Luxury",
    "iX": "EV",
    "Captiva": "SUV",
    "New": "Unknown",
    "BOLERO": "SUV",
    "Windsor": "EV",
    "eC3": "EV",
    "A": "Luxury",
    "Kylaq": "SUV",
    "Invicto": "MUV",
    "C5": "SUV",
    "Grande": "SUV",
    "M-Class": "Luxury",
    "EQB": "EV",
    "LX": "SUV",
    "Bentayga": "Luxury",
    "X-Trail": "SUV",
    "Avventura": "SUV",
    "Aircross": "SUV",
    "Land": "SUV",
    "CLS-Class": "Luxury",
    "F620": "SUV",
    "Revuelto": "Luxury",
    "XE": "Luxury",
    "Venture": "MUV",
    "Kizashi": "Sedan",
    "V40": "Luxury",
    "e2o": "EV",
    "Trailblazer": "SUV",
    "MU": "SUV",
    "Outlander": "SUV",
    "Avigo": "Hatchback"
}

segment_mapping.update(additional_segment_mapping)

In [40]:
vehicle_list["Segment"] = vehicle_list["Vehicle_name"].map(segment_mapping)

In [41]:
vehicle_list[vehicle_list["Segment"].isnull()]

    Vehicle_name Segment
41             S     NaN
50            Q2     NaN
51        Baleno     NaN
52           EON     NaN
53        Hector     NaN
..           ...     ...
205         Jeep     NaN
206        Kicks     NaN
207      Leyland     NaN
208      Renault     NaN
209  Continental     NaN

[161 rows x 2 columns]

In [42]:
vehicle_list["Segment"].isnull().sum()

np.int64(161)

In [43]:
unmapped_vehicles = vehicle_list[
    vehicle_list["Segment"].isnull()
]["Vehicle_name"]

print("Total Unmapped:", len(unmapped_vehicles))

for i, vehicle in enumerate(unmapped_vehicles, start=1):
    print(i, vehicle)

Total Unmapped: 161
1 S
2 Q2
3 Baleno
4 EON
5 Hector
6 KUV
7 Seltos
8 XL6
9 Gurkha
10 Ertiga
11 Brio
12 Brezza
13 Alto
14 E-Class
15 Triber
16 Polo
17 Micra
18 Tiago
19 Celerio
20 Gloster
21 KWID
22 Compass
23 Duster
24 Ritz
25 WR-V
26 Corolla
27 XUV300
28 Taigun
29 Marazzo
30 Safari
31 A4
32 Rover
33 S-Presso
34 A-Star
35 S60
36 XUV700
37 Magnite
38 Zest
39 Astor
40 GO
41 Elantra
42 Jazz
43 Tucson
44 Freestyle
45 Carens
46 Tigor
47 XF
48 Kiger
49 BR-V
50 XC60
51 Indigo
52 Getz
53 Sunny
54 Xcent
55 Quanto
56 Curvv
57 Jimny
58 5
59 Aura
60 Terrano
61 A3
62 7
63 Fluence
64 Kodiaq
65 Indica
66 Elevate
67 Ikon
68 Manza
69 1
70 Lodgy
71 Accent
72 Hexa
73 Tavera
74 A8
75 CLA
76 A6
77 3
78 FRONX
79 Comet
80 GLS
81 Kushaq
82 Q3
83 X1
84 Q5
85 Aspire
86 Enjoy
87 Eeco
88 GLE
89 ZS
90 Cooper
91 Carnival
92 X7
93 S-Class
94 Aveo
95 C-Class
96 6
97 Gypsy
98 SX4
99 Verito
100 Punto
101 CrossPolo
102 F-Pace
103 Q7
104 Nano
105 Cruze
106 GLA
107 Tiguan
108 IONIQ
109 GLC
110 AMG
111 Pajero
112 Passat
113 Slavia
114 Spark
115 MU-X
116 ES
117 X3
118 CR-V
119 Virtus
120 Aria
121 Scala
122 Yeti
123 X5
124 XC90
125 Supro
126 XUV
127 Xylo
128 Civic
129 NuvoSport
130 Omni
131 Hyryder
132 Q8
133 Camry
134 Yodha
135 G-Class
136 Yaris
137 911
138 Bolt
139 Estilo
140 Syros
141 Zen
142 GTR
143 Xenon
144 Willys
145 S90
146 E6
147 Lancer
148 XUV400
149 Captur
150 Pulse
151 BE
152 Cayenne
153 Linea
154 One
155 Dzire
156 C3
157 Jeep
158 Kicks
159 Leyland
160 Renault
161 Continental

In [44]:
additional_segment_mapping = {
    "S": "Luxury",
    "Q2": "SUV",
    "Baleno": "Hatchback",
    "EON": "Hatchback",
    "Hector": "SUV",
    "KUV": "SUV",
    "Seltos": "SUV",
    "XL6": "MUV",
    "Gurkha": "SUV",
    "Ertiga": "MUV",
    "Brio": "Hatchback",
    "Brezza": "SUV",
    "Alto": "Hatchback",
    "E-Class": "Luxury",
    "Triber": "MUV",
    "Polo": "Hatchback",
    "Micra": "Hatchback",
    "Tiago": "Hatchback",
    "Celerio": "Hatchback",
    "Gloster": "SUV",
    "KWID": "Hatchback",
    "Compass": "SUV",
    "Duster": "SUV",
    "Ritz": "Hatchback",
    "WR-V": "SUV",
    "Corolla": "Sedan",
    "XUV300": "SUV",
    "Taigun": "SUV",
    "Marazzo": "MUV",
    "Safari": "SUV",
    "A4": "Luxury",
    "Rover": "Luxury",
    "S-Presso": "Hatchback",
    "A-Star": "Hatchback",
    "S60": "Luxury",
    "XUV700": "SUV",
    "Magnite": "SUV",
    "Zest": "Sedan",
    "Astor": "SUV",
    "GO": "Hatchback",
    "Elantra": "Sedan",
    "Jazz": "Hatchback",
    "Tucson": "SUV",
    "Freestyle": "Hatchback",
    "Carens": "MUV",
    "Tigor": "Sedan",
    "XF": "Luxury",
    "Kiger": "SUV",
    "BR-V": "MUV",
    "XC60": "Luxury",
    "Indigo": "Sedan",
    "Getz": "Hatchback",
    "Sunny": "Sedan",
    "Xcent": "Sedan",
    "Quanto": "SUV",
    "Curvv": "SUV",
    "Jimny": "SUV",
    "5": "Luxury",
    "Aura": "Sedan",
    "Terrano": "SUV",
    "A3": "Luxury",
    "7": "Luxury",
    "Fluence": "Sedan",
    "Kodiaq": "SUV",
    "Indica": "Hatchback",
    "Elevate": "SUV",
    "Ikon": "Sedan",
    "Manza": "Sedan",
    "1": "Luxury",
    "Lodgy": "MUV",
    "Accent": "Sedan",
    "Hexa": "MUV",
    "Tavera": "MUV",
    "A8": "Luxury",
    "CLA": "Luxury",
    "A6": "Luxury",
    "3": "Luxury",
    "FRONX": "SUV",
    "Comet": "EV",
    "GLS": "Luxury",
    "Kushaq": "SUV",
    "Q3": "Luxury",
    "X1": "Luxury",
    "Q5": "Luxury",
    "Aspire": "Sedan",
    "Enjoy": "MUV",
    "Eeco": "MUV",
    "GLE": "Luxury",
    "ZS": "EV",
    "Cooper": "Luxury",
    "Carnival": "MUV",
    "X7": "Luxury",
    "S-Class": "Luxury",
    "Aveo": "Sedan",
    "C-Class": "Luxury",
    "6": "Luxury",
    "Gypsy": "SUV",
    "SX4": "Sedan",
    "Verito": "Sedan",
    "Punto": "Hatchback",
    "CrossPolo": "Hatchback",
    "F-Pace": "Luxury",
    "Q7": "Luxury",
    "Nano": "Hatchback",
    "Cruze": "Sedan",
    "GLA": "Luxury",
    "Tiguan": "SUV",
    "IONIQ": "EV",
    "GLC": "Luxury",
    "AMG": "Luxury",
    "Pajero": "SUV",
    "Passat": "Sedan",
    "Slavia": "Sedan",
    "Spark": "Hatchback",
    "MU-X": "SUV",
    "ES": "Luxury",
    "X3": "Luxury",
    "CR-V": "SUV",
    "Virtus": "Sedan",
    "Aria": "MUV",
    "Scala": "Sedan",
    "Yeti": "SUV",
    "X5": "Luxury",
    "XC90": "Luxury",
    "Supro": "MUV",
    "XUV": "SUV",
    "Xylo": "MUV",
    "Civic": "Sedan",
    "NuvoSport": "SUV",
    "Omni": "MUV",
    "Hyryder": "SUV",
    "Q8": "Luxury",
    "Camry": "Luxury",
    "Yodha": "Pickup",
    "G-Class": "Luxury",
    "Yaris": "Sedan",
    "911": "Luxury",
    "Bolt": "Hatchback",
    "Estilo": "Hatchback",
    "Syros": "SUV",
    "Zen": "Hatchback",
    "GTR": "Luxury",
    "Xenon": "Pickup",
    "Willys": "SUV",
    "S90": "Luxury",
    "E6": "EV",
    "Lancer": "Sedan",
    "XUV400": "EV",
    "Captur": "SUV",
    "Pulse": "Hatchback",
    "BE": "EV",
    "Cayenne": "Luxury",
    "Linea": "Sedan",
    "One": "Luxury",
    "Dzire": "Sedan",
    "C3": "Hatchback",
    "Jeep": "SUV",
    "Kicks": "SUV",
    "Leyland": "Pickup",
    "Renault": "Unknown",
    "Continental": "Luxury"
}

In [45]:
segment_mapping.update(additional_segment_mapping)

vehicle_list["Segment"] = vehicle_list["Vehicle_name"].map(segment_mapping)

vehicle_list["Segment"].isnull().sum()

np.int64(0)

In [46]:
dim_segment = (
    vehicle_list[["Segment"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

dim_segment["Segment_ID"] = dim_segment.index + 1

dim_segment = dim_segment[["Segment_ID", "Segment"]]

dim_segment

   Segment_ID    Segment
0           1      Sedan
1           2  Hatchback
2           3        SUV
3           4        MUV
4           5     Luxury
5           6         EV
6           7     Pickup
7           8    Unknown

In [47]:
dim_segment["Segment"].duplicated().sum()

np.int64(0)

In [48]:
dim_segment.to_csv(
    "Used_Car_Analytics_Output/Dim_Segment.csv",
    index=False
)

In [49]:
df = df.merge(
    dim_brand,
    on="Car_Brand",
    how="left"
)

df.head()

,Car_Brand,Vehicle_name,Car_Model,Year_of_Manufacture,Vehicle_Age,Insurance,Fuel_Type,Seats_Capacity,Kms_Driven,RTO,...,Engine_Displacement,Transmission,Power_Bhp,Drive_Type,Mileage_WRT_Fuel,New_Vehicle_Price_Lakh,Vehicle_Price_Lakh,depreciation(%),Other_Features,Brand_ID
0,Toyota,Etios,NaN,2013,12,Expired,Diesel,5,150000,Sri Ganganagar,...,1364.0,Manual,NaN,NaN,NaN,8.05,2.60,67.70,NaN,1
1,Toyota,Glanza,NaN,2024,1,Expired,Petrol,5,10000,dasuya,...,1197.0,Manual,NaN,NaN,NaN,11.28,9.40,16.67,NaN,1
2,Hyundai,Creta,1.4 E,2017,8,Comprehensive,Diesel,5,75000,Gurgaon,...,1396.0,Manual,NaN,NaN,NaN,11.86,6.25,47.30,NaN,2
3,Volkswagen,Vento,Diesel,2011,14,Expired,Diesel,5,160000,jalalabad,...,1598.0,Manual,103.6,NaN,20.54,10.05,1.40,86.07,['Parking Sensors'],3
4,Hyundai,Verna,1.6,2014,11,Expired,Diesel,5,120000,Meerut,...,1582.0,Manual,126.3,NaN,22.32,11.87,4.00,66.30,"['Automatic Climate Control', 'Parking Sensors']",2

In [50]:
df["Brand_ID"].isnull().sum()

np.int64(0)

In [51]:
df = df.merge(
    dim_model,
    on="Car_Model",
    how="left"
)

df.head()

,Car_Brand,Vehicle_name,Car_Model,Year_of_Manufacture,Vehicle_Age,Insurance,Fuel_Type,Seats_Capacity,Kms_Driven,RTO,...,Transmission,Power_Bhp,Drive_Type,Mileage_WRT_Fuel,New_Vehicle_Price_Lakh,Vehicle_Price_Lakh,depreciation(%),Other_Features,Brand_ID,Model_ID
0,Toyota,Etios,NaN,2013,12,Expired,Diesel,5,150000,Sri Ganganagar,...,Manual,NaN,NaN,NaN,8.05,2.60,67.70,NaN,1,NaN
1,Toyota,Glanza,NaN,2024,1,Expired,Petrol,5,10000,dasuya,...,Manual,NaN,NaN,NaN,11.28,9.40,16.67,NaN,1,NaN
2,Hyundai,Creta,1.4 E,2017,8,Comprehensive,Diesel,5,75000,Gurgaon,...,Manual,NaN,NaN,NaN,11.86,6.25,47.30,NaN,2,1.0
3,Volkswagen,Vento,Diesel,2011,14,Expired,Diesel,5,160000,jalalabad,...,Manual,103.6,NaN,20.54,10.05,1.40,86.07,['Parking Sensors'],3,2.0
4,Hyundai,Verna,1.6,2014,11,Expired,Diesel,5,120000,Meerut,...,Manual,126.3,NaN,22.32,11.87,4.00,66.30,"['Automatic Climate Control', 'Parking Sensors']",2,3.0

In [52]:
df["Model_ID"].isnull().sum()

np.int64(1619)

In [53]:
df = df.merge(
    vehicle_list[["Vehicle_name", "Segment"]],
    on="Vehicle_name",
    how="left"
)

df.head()

,Car_Brand,Vehicle_name,Car_Model,Year_of_Manufacture,Vehicle_Age,Insurance,Fuel_Type,Seats_Capacity,Kms_Driven,RTO,...,Power_Bhp,Drive_Type,Mileage_WRT_Fuel,New_Vehicle_Price_Lakh,Vehicle_Price_Lakh,depreciation(%),Other_Features,Brand_ID,Model_ID,Segment
0,Toyota,Etios,NaN,2013,12,Expired,Diesel,5,150000,Sri Ganganagar,...,NaN,NaN,NaN,8.05,2.60,67.70,NaN,1,NaN,Sedan
1,Toyota,Glanza,NaN,2024,1,Expired,Petrol,5,10000,dasuya,...,NaN,NaN,NaN,11.28,9.40,16.67,NaN,1,NaN,Hatchback
2,Hyundai,Creta,1.4 E,2017,8,Comprehensive,Diesel,5,75000,Gurgaon,...,NaN,NaN,NaN,11.86,6.25,47.30,NaN,2,1.0,SUV
3,Volkswagen,Vento,Diesel,2011,14,Expired,Diesel,5,160000,jalalabad,...,103.6,NaN,20.54,10.05,1.40,86.07,['Parking Sensors'],3,2.0,Sedan
4,Hyundai,Verna,1.6,2014,11,Expired,Diesel,5,120000,Meerut,...,126.3,NaN,22.32,11.87,4.00,66.30,"['Automatic Climate Control', 'Parking Sensors']",2,3.0,Sedan

In [54]:
df["Segment"].isnull().sum()

np.int64(0)

In [55]:
df = df.merge(
    dim_segment,
    on="Segment",
    how="left"
)

df.head()

,Car_Brand,Vehicle_name,Car_Model,Year_of_Manufacture,Vehicle_Age,Insurance,Fuel_Type,Seats_Capacity,Kms_Driven,RTO,...,Drive_Type,Mileage_WRT_Fuel,New_Vehicle_Price_Lakh,Vehicle_Price_Lakh,depreciation(%),Other_Features,Brand_ID,Model_ID,Segment,Segment_ID
0,Toyota,Etios,NaN,2013,12,Expired,Diesel,5,150000,Sri Ganganagar,...,NaN,NaN,8.05,2.60,67.70,NaN,1,NaN,Sedan,1
1,Toyota,Glanza,NaN,2024,1,Expired,Petrol,5,10000,dasuya,...,NaN,NaN,11.28,9.40,16.67,NaN,1,NaN,Hatchback,2
2,Hyundai,Creta,1.4 E,2017,8,Comprehensive,Diesel,5,75000,Gurgaon,...,NaN,NaN,11.86,6.25,47.30,NaN,2,1.0,SUV,3
3,Volkswagen,Vento,Diesel,2011,14,Expired,Diesel,5,160000,jalalabad,...,NaN,20.54,10.05,1.40,86.07,['Parking Sensors'],3,2.0,Sedan,1
4,Hyundai,Verna,1.6,2014,11,Expired,Diesel,5,120000,Meerut,...,NaN,22.32,11.87,4.00,66.30,"['Automatic Climate Control', 'Parking Sensors']",2,3.0,Sedan,1

In [56]:
df["Segment_ID"].isnull().sum()

np.int64(0)

In [57]:
df = df.drop(
    columns=[
        "Car_Brand",
        "Car_Model",
        "Segment"
    ]
)

In [58]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10224 entries, 0 to 10223
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Vehicle_name            10224 non-null  str
 1   Year_of_Manufacture     10224 non-null  int64
 2   Vehicle_Age             10224 non-null  int64
 3   Insurance               10224 non-null  str
 4   Fuel_Type               10224 non-null  str
 5   Seats_Capacity          10224 non-null  int64
 6   Kms_Driven              10224 non-null  int64
 7   RTO                     10224 non-null  str
 8   Ownership               10221 non-null  str
 9   Engine_Displacement     10142 non-null  float64
 10  Transmission            10224 non-null  str
 11  Power_Bhp               7098 non-null   float64
 12  Drive_Type              2247 non-null   str
 13  Mileage_WRT_Fuel        6809 non-null   float64
 14  New_Vehicle_Price_Lakh  10224 non-null  float64
 15  Vehicle_Price_Lakh      10224 non-null  float64
 16  depreciation(%)         10224 non-null  float64
 17  Other_Features          6378 non-null   str
 18  Brand_ID                10224 non-null  int64
 19  Model_ID                8605 non-null   float64
 20  Segment_ID              10224 non-null  int64
dtypes: float64(7), int64(6), str(8)
memory usage: 2.5 MB

In [59]:
df[
[
"Vehicle_Age",
"Kms_Driven",
"Ownership",
"depreciation(%)"
]
].head()

   Vehicle_Age  Kms_Driven     Ownership  depreciation(%)
0           12      150000  Fourth Owner            67.70
1            1       10000   First Owner            16.67
2            8       75000   First Owner            47.30
3           14      160000   Third Owner            86.07
4           11      120000   First Owner            66.30

In [60]:
def depreciation_score(value):
    if value <= 20:
        return 10
    elif value <= 40:
        return 8
    elif value <= 60:
        return 6
    else:
        return 4

df["Depreciation_Score"] = df["depreciation(%)"].apply(depreciation_score)

In [61]:
df[
[
"depreciation(%)",
"Depreciation_Score"
]
].head()

   depreciation(%)  Depreciation_Score
0            67.70                   4
1            16.67                  10
2            47.30                   6
3            86.07                   4
4            66.30                   4

In [62]:
def age_score(value):
    if value <= 3:
        return 10
    elif value <= 6:
        return 8
    elif value <= 10:
        return 6
    else:
        return 4

df["Age_Score"] = df["Vehicle_Age"].apply(age_score)

In [63]:
def kms_score(value):
    if value <= 50000:
        return 10
    elif value <= 100000:
        return 8
    elif value <= 150000:
        return 6
    else:
        return 4

df["Kms_Score"] = df["Kms_Driven"].apply(kms_score)

In [64]:
def ownership_score(value):
    if value == "First Owner":
        return 10
    elif value == "Second Owner":
        return 8
    elif value == "Third Owner":
        return 6
    else:
        return 4

df["Ownership_Score"] = df["Ownership"].apply(ownership_score)

In [65]:
df["Value_for_Money_Score"] = (
    (df["Depreciation_Score"] * 0.40)
    +
    (df["Age_Score"] * 0.30)
    +
    (df["Kms_Score"] * 0.20)
    +
    (df["Ownership_Score"] * 0.10)
)

In [66]:
df["Value_for_Money_Score"] = df["Value_for_Money_Score"].round(1)

In [67]:
df[
[
"Vehicle_name",
"Vehicle_Age",
"Kms_Driven",
"Ownership",
"depreciation(%)",
"Value_for_Money_Score"
]
].head(20)

,Vehicle_name,Vehicle_Age,Kms_Driven,Ownership,depreciation(%),Value_for_Money_Score
0,Etios,12,150000,Fourth Owner,67.70,4.4
1,Glanza,1,10000,First Owner,16.67,10.0
2,Creta,8,75000,First Owner,47.30,6.8
3,Vento,14,160000,Third Owner,86.07,4.2
4,Verna,11,120000,First Owner,66.30,5.0
5,Santro,13,147000,Third Owner,78.77,4.6
6,i20,2,9400,First Owner,18.93,10.0
7,Harrier,4,50000,First Owner,41.27,7.8
8,Nexon,6,71000,Second Owner,50.91,7.2
9,Creta,7,81000,Second Owner,37.74,7.4
10,Bolero,11,196472,Third Owner,53.31,5.0
11,XUV500,8,110000,First Owner,65.19,5.6
12,Vitara,7,77000,Second Owner,37.44,7.4
13,Swift,5,65000,First Owner,22.67,8.2
14,Bolero,11,175847,First Owner,45.73,5.4
15,Creta,4,79000,First Owner,22.97,8.2
16,Octavia,11,90463,Second Owner,73.86,5.2
17,Rapid,8,92500,First Owner,60.11,6.0
18,Ciaz,9,80000,Second Owner,58.75,6.6
19,Laura,14,90000,Third Owner,81.40,5.0

In [68]:
df["Value_for_Money_Score"].describe()

count    10224.000000
mean         7.287617
std          1.670850
min          4.000000
25%          5.800000
50%          7.200000
75%          8.600000
max         10.000000
Name: Value_for_Money_Score, dtype: float64

In [69]:
df = df.rename(columns={
    "Vehicle_name": "Vehicle_Name",
    "RTO": "RTO_Location",
    "Power_Bhp": "Power_BHP",
    "Mileage_WRT_Fuel": "Mileage_By_Fuel_Type",
    "depreciation(%)": "Depreciation_Percentage",
    "Value_for_Money_Score": "Value_For_Money_Score"
})

df.columns

Index(['Vehicle_Name', 'Year_of_Manufacture', 'Vehicle_Age', 'Insurance',
       'Fuel_Type', 'Seats_Capacity', 'Kms_Driven', 'RTO_Location',
       'Ownership', 'Engine_Displacement', 'Transmission', 'Power_BHP',
       'Drive_Type', 'Mileage_By_Fuel_Type', 'New_Vehicle_Price_Lakh',
       'Vehicle_Price_Lakh', 'Depreciation_Percentage', 'Other_Features',
       'Brand_ID', 'Model_ID', 'Segment_ID', 'Depreciation_Score', 'Age_Score',
       'Kms_Score', 'Ownership_Score', 'Value_For_Money_Score'],
      dtype='str')

In [70]:
import pandas as pd
import numpy as np
import re

df.columns = (
    df.columns
    .str.strip()
    .str.replace(" ", "_")
    .str.replace(r"[^\w]", "", regex=True)
)

text_columns = df.select_dtypes(include="object").columns

for col in text_columns:
    df[col] = (
        df[col]
        .astype(str)
        .str.strip()
        .replace(
            ["", "nan", "None", "NULL", "null", "[]"],
            np.nan
        )
    )

df = df.drop_duplicates()

df = df.reset_index(drop=True)

df.columns

C:\Users\sahil\AppData\Local\Temp\ipykernel_4300\1367627558.py:12: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include="object").columns

Index(['Vehicle_Name', 'Year_of_Manufacture', 'Vehicle_Age', 'Insurance',
       'Fuel_Type', 'Seats_Capacity', 'Kms_Driven', 'RTO_Location',
       'Ownership', 'Engine_Displacement', 'Transmission', 'Power_BHP',
       'Drive_Type', 'Mileage_By_Fuel_Type', 'New_Vehicle_Price_Lakh',
       'Vehicle_Price_Lakh', 'Depreciation_Percentage', 'Other_Features',
       'Brand_ID', 'Model_ID', 'Segment_ID', 'Depreciation_Score', 'Age_Score',
       'Kms_Score', 'Ownership_Score', 'Value_For_Money_Score'],
      dtype='str')

In [71]:
for col in text_columns:
    check = df[col].astype(str).str.contains(r"^\s|\s$", regex=True).sum()
    print(col, check)

Vehicle_Name 0
Insurance 0
Fuel_Type 0
RTO_Location 0
Ownership 0
Transmission 0
Drive_Type 0
Other_Features 0

In [72]:
df.isnull().sum()

Vehicle_Name                  0
Year_of_Manufacture           0
Vehicle_Age                   0
Insurance                     0
Fuel_Type                     0
Seats_Capacity                0
Kms_Driven                    0
RTO_Location                  0
Ownership                     3
Engine_Displacement          81
Transmission                  0
Power_BHP                  3109
Drive_Type                 7919
Mileage_By_Fuel_Type       3395
New_Vehicle_Price_Lakh        0
Vehicle_Price_Lakh            0
Depreciation_Percentage       0
Other_Features             3823
Brand_ID                      0
Model_ID                   1604
Segment_ID                    0
Depreciation_Score            0
Age_Score                     0
Kms_Score                     0
Ownership_Score               0
Value_For_Money_Score         0
dtype: int64

In [73]:
df[df["Ownership"].isnull()]

,Vehicle_Name,Year_of_Manufacture,Vehicle_Age,Insurance,Fuel_Type,Seats_Capacity,Kms_Driven,RTO_Location,Ownership,Engine_Displacement,...,Depreciation_Percentage,Other_Features,Brand_ID,Model_ID,Segment_ID,Depreciation_Score,Age_Score,Kms_Score,Ownership_Score,Value_For_Money_Score
1314,Taigun,2024,1,Expired,Petrol,5,15000,Unknown,NaN,999.0,...,16.34,"['Ventilated Seats', 'Height Adjustable Driver...",3,520.0,3,10,10,10,4,9.4
1900,XUV700,2025,0,Comprehensive,Diesel,7,491,Unknown,NaN,2198.0,...,8.22,NaN,5,175.0,3,10,10,10,4,9.4
5109,Q3,2024,1,Expired,Petrol,5,6691,Unknown,NaN,1984.0,...,32.44,"['Powered Front Seats', 'Height Adjustable Dri...",13,1199.0,5,8,10,10,4,8.6

In [74]:
df["Ownership"] = df["Ownership"].fillna("Unknown")

In [75]:
df["Drive_Type"] = df["Drive_Type"].fillna("Unknown")

In [76]:
df["Other_Features"] = df["Other_Features"].fillna("No_Features")

In [77]:
unknown_model_id = dim_model["Model_ID"].max() + 1

unknown_row = pd.DataFrame({
    "Model_ID":[unknown_model_id],
    "Car_Model":["Unknown"]
})

dim_model = pd.concat(
    [dim_model, unknown_row],
    ignore_index=True
)

In [78]:
df["Model_ID"] = df["Model_ID"].fillna(unknown_model_id)

In [79]:
df.isnull().sum()

Vehicle_Name                  0
Year_of_Manufacture           0
Vehicle_Age                   0
Insurance                     0
Fuel_Type                     0
Seats_Capacity                0
Kms_Driven                    0
RTO_Location                  0
Ownership                     0
Engine_Displacement          81
Transmission                  0
Power_BHP                  3109
Drive_Type                    0
Mileage_By_Fuel_Type       3395
New_Vehicle_Price_Lakh        0
Vehicle_Price_Lakh            0
Depreciation_Percentage       0
Other_Features                0
Brand_ID                      0
Model_ID                      0
Segment_ID                    0
Depreciation_Score            0
Age_Score                     0
Kms_Score                     0
Ownership_Score               0
Value_For_Money_Score         0
dtype: int64

In [80]:
df["Power_BHP"].apply(type).value_counts()

Power_BHP
<class 'float'>    10143
Name: count, dtype: int64

In [81]:
df["Engine_Displacement"].apply(type).value_counts()

Engine_Displacement
<class 'float'>    10143
Name: count, dtype: int64

In [82]:
df["Mileage_By_Fuel_Type"].apply(type).value_counts()

Mileage_By_Fuel_Type
<class 'float'>    10143
Name: count, dtype: int64

In [83]:
df["Other_Features"] = df["Other_Features"].apply(
    lambda x: ", ".join(x) if isinstance(x, list) else x
)

In [84]:
df.dtypes

Vehicle_Name                   str
Year_of_Manufacture          int64
Vehicle_Age                  int64
Insurance                      str
Fuel_Type                      str
Seats_Capacity               int64
Kms_Driven                   int64
RTO_Location                   str
Ownership                      str
Engine_Displacement        float64
Transmission                   str
Power_BHP                  float64
Drive_Type                     str
Mileage_By_Fuel_Type       float64
New_Vehicle_Price_Lakh     float64
Vehicle_Price_Lakh         float64
Depreciation_Percentage    float64
Other_Features                 str
Brand_ID                     int64
Model_ID                   float64
Segment_ID                   int64
Depreciation_Score           int64
Age_Score                    int64
Kms_Score                    int64
Ownership_Score              int64
Value_For_Money_Score      float64
dtype: object

In [85]:
dim_brand["Brand_ID"].duplicated().sum()

dim_model["Model_ID"].duplicated().sum()

dim_segment["Segment_ID"].duplicated().sum()

np.int64(0)

In [86]:
df.isnull().sum()

Vehicle_Name                  0
Year_of_Manufacture           0
Vehicle_Age                   0
Insurance                     0
Fuel_Type                     0
Seats_Capacity                0
Kms_Driven                    0
RTO_Location                  0
Ownership                     0
Engine_Displacement          81
Transmission                  0
Power_BHP                  3109
Drive_Type                    0
Mileage_By_Fuel_Type       3395
New_Vehicle_Price_Lakh        0
Vehicle_Price_Lakh            0
Depreciation_Percentage       0
Other_Features                0
Brand_ID                      0
Model_ID                      0
Segment_ID                    0
Depreciation_Score            0
Age_Score                     0
Kms_Score                     0
Ownership_Score               0
Value_For_Money_Score         0
dtype: int64

In [87]:
df.dtypes

Vehicle_Name                   str
Year_of_Manufacture          int64
Vehicle_Age                  int64
Insurance                      str
Fuel_Type                      str
Seats_Capacity               int64
Kms_Driven                   int64
RTO_Location                   str
Ownership                      str
Engine_Displacement        float64
Transmission                   str
Power_BHP                  float64
Drive_Type                     str
Mileage_By_Fuel_Type       float64
New_Vehicle_Price_Lakh     float64
Vehicle_Price_Lakh         float64
Depreciation_Percentage    float64
Other_Features                 str
Brand_ID                     int64
Model_ID                   float64
Segment_ID                   int64
Depreciation_Score           int64
Age_Score                    int64
Kms_Score                    int64
Ownership_Score              int64
Value_For_Money_Score      float64
dtype: object

In [88]:
df["Model_ID"] = df["Model_ID"].astype(int)

In [89]:
df["Model_ID"].dtype

dtype('int64')

In [90]:
df["Other_Features"].apply(type).value_counts()

Other_Features
<class 'str'>    10143
Name: count, dtype: int64

In [91]:
df[["Brand_ID","Model_ID","Segment_ID"]].head()

   Brand_ID  Model_ID  Segment_ID
0         1      1705           1
1         1      1705           2
2         2         1           3
3         3         2           1
4         2         3           1

In [92]:
df[["Brand_ID","Model_ID","Segment_ID"]].dtypes

Brand_ID      int64
Model_ID      int64
Segment_ID    int64
dtype: object

In [93]:
df.duplicated().sum()

np.int64(0)

In [94]:
df.columns.tolist()

['Vehicle_Name',
 'Year_of_Manufacture',
 'Vehicle_Age',
 'Insurance',
 'Fuel_Type',
 'Seats_Capacity',
 'Kms_Driven',
 'RTO_Location',
 'Ownership',
 'Engine_Displacement',
 'Transmission',
 'Power_BHP',
 'Drive_Type',
 'Mileage_By_Fuel_Type',
 'New_Vehicle_Price_Lakh',
 'Vehicle_Price_Lakh',
 'Depreciation_Percentage',
 'Other_Features',
 'Brand_ID',
 'Model_ID',
 'Segment_ID',
 'Depreciation_Score',
 'Age_Score',
 'Kms_Score',
 'Ownership_Score',
 'Value_For_Money_Score']

In [95]:
df["Model_ID"] = df["Model_ID"].astype(int)

In [96]:
df.columns.tolist()

['Vehicle_Name',
 'Year_of_Manufacture',
 'Vehicle_Age',
 'Insurance',
 'Fuel_Type',
 'Seats_Capacity',
 'Kms_Driven',
 'RTO_Location',
 'Ownership',
 'Engine_Displacement',
 'Transmission',
 'Power_BHP',
 'Drive_Type',
 'Mileage_By_Fuel_Type',
 'New_Vehicle_Price_Lakh',
 'Vehicle_Price_Lakh',
 'Depreciation_Percentage',
 'Other_Features',
 'Brand_ID',
 'Model_ID',
 'Segment_ID',
 'Depreciation_Score',
 'Age_Score',
 'Kms_Score',
 'Ownership_Score',
 'Value_For_Money_Score']

In [97]:
df.columns.tolist()

['Vehicle_Name',
 'Year_of_Manufacture',
 'Vehicle_Age',
 'Insurance',
 'Fuel_Type',
 'Seats_Capacity',
 'Kms_Driven',
 'RTO_Location',
 'Ownership',
 'Engine_Displacement',
 'Transmission',
 'Power_BHP',
 'Drive_Type',
 'Mileage_By_Fuel_Type',
 'New_Vehicle_Price_Lakh',
 'Vehicle_Price_Lakh',
 'Depreciation_Percentage',
 'Other_Features',
 'Brand_ID',
 'Model_ID',
 'Segment_ID',
 'Depreciation_Score',
 'Age_Score',
 'Kms_Score',
 'Ownership_Score',
 'Value_For_Money_Score']

In [98]:
df.to_csv(
    "Used_Car_Analytics_Output/Fact_Used_Cars_Final.csv",
    index=False
)

In [99]:
df.shape

(10143, 26)

In [100]:
df.info

<bound method DataFrame.info of       Vehicle_Name  Year_of_Manufacture  Vehicle_Age      Insurance Fuel_Type  \
0            Etios                 2013           12        Expired    Diesel
1           Glanza                 2024            1        Expired    Petrol
2            Creta                 2017            8  Comprehensive    Diesel
3            Vento                 2011           14        Expired    Diesel
4            Verna                 2014           11        Expired    Diesel
...            ...                  ...          ...            ...       ...
10138       XUV500                 2014           11        Expired    Diesel
10139        Wagon                 2015           10        Expired       CNG
10140        Swift                 2019            6        Expired    Petrol
10141       Accent                 2009           16        Expired    Petrol
10142          GLC                 2018            7        Expired    Diesel

       Seats_Capacity  Kms_Driven    RTO_Location     Ownership  \
0                   5      150000  Sri Ganganagar  Fourth Owner
1                   5       10000          dasuya   First Owner
2                   5       75000         Gurgaon   First Owner
3                   5      160000       jalalabad   Third Owner
4                   5      120000          Meerut   First Owner
...               ...         ...             ...           ...
10138               7      150000      Chandigarh   First Owner
10139               5      120000         Gurgaon  Second Owner
10140               5       80000      Chandigarh   First Owner
10141               5       60000      Chandigarh  Second Owner
10142               5       60000          Mohali   First Owner

       Engine_Displacement  ... Depreciation_Percentage  \
0                   1364.0  ...                   67.70
1                   1197.0  ...                   16.67
2                   1396.0  ...                   47.30
3                   1598.0  ...                   86.07
4                   1582.0  ...                   66.30
...                    ...  ...                     ...
10138               2179.0  ...                   77.63
10139                998.0  ...                   50.82
10140               1197.0  ...                   20.24
10141               1495.0  ...                   86.62
10142               2143.0  ...                   51.35

                                          Other_Features Brand_ID  Model_ID  \
0                                            No_Features        1      1705
1                                            No_Features        1      1705
2                                            No_Features        2         1
3                                    ['Parking Sensors']        3         2
4       ['Automatic Climate Control', 'Parking Sensors']        2         3
...                                                  ...      ...       ...
10138  ['Air Purifier', 'Automatic Climate Control', ...        5       206
10139  ['Central Locking', 'Air Conditioner', 'Digita...        6        20
10140               ['Rear AC Vents', 'Parking Sensors']        6       295
10141                                        No_Features        2      1705
10142                                        No_Features       16      1704

       Segment_ID  Depreciation_Score  Age_Score Kms_Score  Ownership_Score  \
0               1                   4          4         6                4
1               2                  10         10        10               10
2               3                   6          6         8               10
3               1                   4          4         4                6
4               1                   4          4         6               10
...           ...                 ...        ...       ...              ...
10138           3                   4          4         6               10
10139           2                   6          6         6                8
10140           2                   8          8         8               10
10141           1                   4          4         8                8
10142           5                   6          6         8               10

       Value_For_Money_Score
0                        4.4
1                       10.0
2                        6.8
3                        4.2
4                        5.0
...                      ...
10138                    5.0
10139                    6.2
10140                    8.2
10141                    5.2
10142                    6.8

[10143 rows x 26 columns]>

In [101]:
df = df[
    [
        "Brand_ID",
        "Model_ID",
        "Segment_ID",
        "Vehicle_Name",
        "Year_of_Manufacture",
        "Vehicle_Age",
        "Insurance",
        "Fuel_Type",
        "Seats_Capacity",
        "Kms_Driven",
        "RTO_Location",
        "Ownership",
        "Engine_Displacement",
        "Transmission",
        "Power_BHP",
        "Drive_Type",
        "Mileage_By_Fuel_Type",
        "New_Vehicle_Price_Lakh",
        "Vehicle_Price_Lakh",
        "Depreciation_Percentage",
        "Other_Features",
        "Value_For_Money_Score"
    ]
]

In [102]:
df.to_csv(
    "Used_Car_Analytics_Output/Fact_Used_Cars_Final.csv",
    index=False,
    encoding="utf-8"
)

In [103]:
dim_brand.to_csv(
    "Used_Car_Analytics_Output/Dim_Brand.csv",
    index=False,
    encoding="utf-8"
)

dim_model.to_csv(
    "Used_Car_Analytics_Output/Dim_Model.csv",
    index=False,
    encoding="utf-8"
)

dim_segment.to_csv(
    "Used_Car_Analytics_Output/Dim_Segment.csv",
    index=False,
    encoding="utf-8"
)

In [104]:
print(df.shape)
print(dim_brand.shape)
print(dim_model.shape)
print(dim_segment.shape)

(10143, 22)
(36, 2)
(1705, 2)
(8, 2)

In [105]:
print(df.columns.tolist())

['Brand_ID', 'Model_ID', 'Segment_ID', 'Vehicle_Name', 'Year_of_Manufacture', 'Vehicle_Age', 'Insurance', 'Fuel_Type', 'Seats_Capacity', 'Kms_Driven', 'RTO_Location', 'Ownership', 'Engine_Displacement', 'Transmission', 'Power_BHP', 'Drive_Type', 'Mileage_By_Fuel_Type', 'New_Vehicle_Price_Lakh', 'Vehicle_Price_Lakh', 'Depreciation_Percentage', 'Other_Features', 'Value_For_Money_Score']

In [106]:
len(df.columns)

22

In [107]:
print(df.shape)

(10143, 22)

In [108]:
print(df.info)

<bound method DataFrame.info of        Brand_ID  Model_ID  Segment_ID Vehicle_Name  Year_of_Manufacture  \
0             1      1705           1        Etios                 2013
1             1      1705           2       Glanza                 2024
2             2         1           3        Creta                 2017
3             3         2           1        Vento                 2011
4             2         3           1        Verna                 2014
...         ...       ...         ...          ...                  ...
10138         5       206           3       XUV500                 2014
10139         6        20           2        Wagon                 2015
10140         6       295           2        Swift                 2019
10141         2      1705           1       Accent                 2009
10142        16      1704           5          GLC                 2018

       Vehicle_Age      Insurance Fuel_Type  Seats_Capacity  Kms_Driven  ...  \
0               12        Expired    Diesel               5      150000  ...
1                1        Expired    Petrol               5       10000  ...
2                8  Comprehensive    Diesel               5       75000  ...
3               14        Expired    Diesel               5      160000  ...
4               11        Expired    Diesel               5      120000  ...
...            ...            ...       ...             ...         ...  ...
10138           11        Expired    Diesel               7      150000  ...
10139           10        Expired       CNG               5      120000  ...
10140            6        Expired    Petrol               5       80000  ...
10141           16        Expired    Petrol               5       60000  ...
10142            7        Expired    Diesel               5       60000  ...

      Engine_Displacement Transmission  Power_BHP Drive_Type  \
0                  1364.0       Manual        NaN    Unknown
1                  1197.0       Manual        NaN    Unknown
2                  1396.0       Manual        NaN    Unknown
3                  1598.0       Manual     103.60    Unknown
4                  1582.0       Manual     126.30    Unknown
...                   ...          ...        ...        ...
10138              2179.0       Manual     140.00        AWD
10139               998.0       Manual      58.16    Unknown
10140              1197.0    Automatic      81.80    Unknown
10141              1495.0       Manual      93.70    Unknown
10142              2143.0    Automatic        NaN    Unknown

       Mileage_By_Fuel_Type New_Vehicle_Price_Lakh  Vehicle_Price_Lakh  \
0                       NaN                   8.05                2.60
1                       NaN                  11.28                9.40
2                       NaN                  11.86                6.25
3                     20.54                  10.05                1.40
4                     22.32                  11.87                4.00
...                     ...                    ...                 ...
10138                 15.10                  17.88                4.00
10139                 26.60                   5.49                2.70
10140                 21.21                   8.40                6.70
10141                 16.36                   5.98                0.80
10142                   NaN                  61.66               30.00

       Depreciation_Percentage  \
0                        67.70
1                        16.67
2                        47.30
3                        86.07
4                        66.30
...                        ...
10138                    77.63
10139                    50.82
10140                    20.24
10141                    86.62
10142                    51.35

                                          Other_Features  \
0                                            No_Features
1                                            No_Features
2                                            No_Features
3                                    ['Parking Sensors']
4       ['Automatic Climate Control', 'Parking Sensors']
...                                                  ...
10138  ['Air Purifier', 'Automatic Climate Control', ...
10139  ['Central Locking', 'Air Conditioner', 'Digita...
10140               ['Rear AC Vents', 'Parking Sensors']
10141                                        No_Features
10142                                        No_Features

       Value_For_Money_Score
0                        4.4
1                       10.0
2                        6.8
3                        4.2
4                        5.0
...                      ...
10138                    5.0
10139                    6.2
10140                    8.2
10141                    5.2
10142                    6.8

[10143 rows x 22 columns]>

In [109]:
df.dtypes

Brand_ID                     int64
Model_ID                     int64
Segment_ID                   int64
Vehicle_Name                   str
Year_of_Manufacture          int64
Vehicle_Age                  int64
Insurance                      str
Fuel_Type                      str
Seats_Capacity               int64
Kms_Driven                   int64
RTO_Location                   str
Ownership                      str
Engine_Displacement        float64
Transmission                   str
Power_BHP                  float64
Drive_Type                     str
Mileage_By_Fuel_Type       float64
New_Vehicle_Price_Lakh     float64
Vehicle_Price_Lakh         float64
Depreciation_Percentage    float64
Other_Features                 str
Value_For_Money_Score      float64
dtype: object

In [110]:
print(df.shape)
print(dim_brand.shape)
print(dim_model.shape)
print(dim_segment.shape)

(10143, 22)
(36, 2)
(1705, 2)
(8, 2)

In [111]:
print(df.duplicated().sum())

0

In [112]:
print(dim_brand.duplicated().sum())
print(dim_model.duplicated().sum())
print(dim_segment.duplicated().sum())

0
0
0

In [113]:
print(df.isnull().sum())

Brand_ID                      0
Model_ID                      0
Segment_ID                    0
Vehicle_Name                  0
Year_of_Manufacture           0
Vehicle_Age                   0
Insurance                     0
Fuel_Type                     0
Seats_Capacity                0
Kms_Driven                    0
RTO_Location                  0
Ownership                     0
Engine_Displacement          81
Transmission                  0
Power_BHP                  3109
Drive_Type                    0
Mileage_By_Fuel_Type       3395
New_Vehicle_Price_Lakh        0
Vehicle_Price_Lakh            0
Depreciation_Percentage       0
Other_Features                0
Value_For_Money_Score         0
dtype: int64

In [114]:
print(df.dtypes)

Brand_ID                     int64
Model_ID                     int64
Segment_ID                   int64
Vehicle_Name                   str
Year_of_Manufacture          int64
Vehicle_Age                  int64
Insurance                      str
Fuel_Type                      str
Seats_Capacity               int64
Kms_Driven                   int64
RTO_Location                   str
Ownership                      str
Engine_Displacement        float64
Transmission                   str
Power_BHP                  float64
Drive_Type                     str
Mileage_By_Fuel_Type       float64
New_Vehicle_Price_Lakh     float64
Vehicle_Price_Lakh         float64
Depreciation_Percentage    float64
Other_Features                 str
Value_For_Money_Score      float64
dtype: object

In [115]:
print(df.columns.tolist())

['Brand_ID', 'Model_ID', 'Segment_ID', 'Vehicle_Name', 'Year_of_Manufacture', 'Vehicle_Age', 'Insurance', 'Fuel_Type', 'Seats_Capacity', 'Kms_Driven', 'RTO_Location', 'Ownership', 'Engine_Displacement', 'Transmission', 'Power_BHP', 'Drive_Type', 'Mileage_By_Fuel_Type', 'New_Vehicle_Price_Lakh', 'Vehicle_Price_Lakh', 'Depreciation_Percentage', 'Other_Features', 'Value_For_Money_Score']

In [116]:
print(df["Brand_ID"].min(), df["Brand_ID"].max())
print(df["Model_ID"].min(), df["Model_ID"].max())
print(df["Segment_ID"].min(), df["Segment_ID"].max())

1 36
1 1705
1 8

In [117]:
print(
    set(df["Brand_ID"]) -
    set(dim_brand["Brand_ID"])
)

set()

In [118]:
print(
    set(df["Model_ID"]) -
    set(dim_model["Model_ID"])
)

set()

In [119]:
print(
    set(df["Segment_ID"]) -
    set(dim_segment["Segment_ID"])
)

set()

In [120]:
print(df.describe())

           Brand_ID      Model_ID    Segment_ID  Year_of_Manufacture  \
count  10143.000000  10143.000000  10143.000000         10143.000000
mean       6.668934    613.244997      2.527852          2017.549837
std        4.972715    615.244332      1.031828             4.600898
min        1.000000      1.000000      1.000000          1985.000000
25%        4.000000    100.000000      2.000000          2014.000000
50%        6.000000    331.000000      2.000000          2018.000000
75%        8.000000   1064.500000      3.000000          2021.000000
max       36.000000   1705.000000      8.000000          2025.000000

        Vehicle_Age  Seats_Capacity    Kms_Driven  Engine_Displacement  \
count  10143.000000    10143.000000  1.014300e+04         10062.000000
mean       7.450163        5.338066  7.865364e+04          1431.728782
std        4.600898        0.828749  2.035869e+05           477.682557
min        0.000000        2.000000  2.500000e+02           624.000000
25%        4.000000        5.000000  4.000000e+04          1197.000000
50%        7.000000        5.000000  7.000000e+04          1248.000000
75%       11.000000        5.000000  1.000000e+05          1498.000000
max       40.000000       10.000000  1.860000e+07          6498.000000

         Power_BHP  Mileage_By_Fuel_Type  New_Vehicle_Price_Lakh  \
count  7034.000000           6748.000000            10143.000000
mean     99.765720             19.944221               14.648435
std      45.710223              3.884997               22.398376
min      25.400000              5.400000                1.450000
25%      73.900000             17.300000                6.960000
50%      87.200000             19.810000                9.740000
75%     113.980000             22.380000               14.690000
max    1001.110000             35.600000             1021.000000

       Vehicle_Price_Lakh  Depreciation_Percentage  Value_For_Money_Score
count        10143.000000             10143.000000           10143.000000
mean             8.149397                43.853054               7.287331
std             13.568254                21.386638               1.670882
min              0.100000               -13.210000               4.000000
25%              3.250000                27.085000               5.800000
50%              5.500000                42.080000               7.200000
75%              9.000000                59.835000               8.600000
max            750.000000                99.780000              10.000000

In [121]:
print(df["Other_Features"].sample(10))

651                                            No_Features
3579                                           No_Features
9381                                           No_Features
3345                                           No_Features
10006    ['Keyless Entry', 'Central Locking', 'Air Cond...
9505     ['Engine Start/Stop Button', 'Automatic Climat...
602      ['Automatic Climate Control', 'Parking Sensors...
857                                    ['Air Conditioner']
1833                                           No_Features
4981     ['Central Locking', 'Air Conditioner', 'Digita...
Name: Other_Features, dtype: str

In [122]:
df[df["Depreciation_Percentage"] < 0]

,Brand_ID,Model_ID,Segment_ID,Vehicle_Name,Year_of_Manufacture,Vehicle_Age,Insurance,Fuel_Type,Seats_Capacity,Kms_Driven,...,Engine_Displacement,Transmission,Power_BHP,Drive_Type,Mileage_By_Fuel_Type,New_Vehicle_Price_Lakh,Vehicle_Price_Lakh,Depreciation_Percentage,Other_Features,Value_For_Money_Score
1771,5,627,3,Scorpio,2023,2,Com + Zero Dep,Petrol,7,25000,...,1997.0,Manual,200.0,2WD,NaN,21.37,21.90,-2.48,"['Height Adjustable Driver Seat', 'Automatic C...",10.0
1915,20,654,5,Rover,2024,1,Comprehensive,Petrol,5,10000,...,1997.0,Automatic,296.0,AWD,NaN,116.00,126.00,-8.62,"['360 Degree Camera', 'Memory Function For Sea...",10.0
2387,18,424,3,Magnite,2024,1,Expired,Petrol,5,6295,...,999.0,Manual,NaN,Unknown,NaN,7.13,7.90,-10.80,No_Features,10.0
5062,5,1705,3,Scorpio,2024,1,Com + Zero Dep,Diesel,7,18539,...,2184.0,Manual,130.0,RWD,14.44,16.12,18.25,-13.21,No_Features,10.0
6720,33,1386,5,Bentayga,2023,2,Com + Zero Dep,Petrol,5,800,...,3998.0,Automatic,542.0,AWD,NaN,689.00,750.00,-8.85,"['Powered Front Seats', 'Ventilated Seats', 'H...",10.0
8969,2,100,3,Creta,2024,1,Third Party,Petrol,5,14500,...,1497.0,Automatic,NaN,Unknown,NaN,19.16,19.19,-0.16,No_Features,10.0

In [123]:
import ast

def clean_features(x):
    if x == "No_Features":
        return "No_Features"

    try:
        return " | ".join(ast.literal_eval(x))
    except:
        return x

df["Other_Features"] = df["Other_Features"].apply(clean_features)

In [124]:
for col in df.columns:
    print(repr(col))

'Brand_ID'
'Model_ID'
'Segment_ID'
'Vehicle_Name'
'Year_of_Manufacture'
'Vehicle_Age'
'Insurance'
'Fuel_Type'
'Seats_Capacity'
'Kms_Driven'
'RTO_Location'
'Ownership'
'Engine_Displacement'
'Transmission'
'Power_BHP'
'Drive_Type'
'Mileage_By_Fuel_Type'
'New_Vehicle_Price_Lakh'
'Vehicle_Price_Lakh'
'Depreciation_Percentage'
'Other_Features'
'Value_For_Money_Score'

In [129]:
with open(r"C:\Users\sahil\OneDrive\Desktop\DATA ANALYTICS HANDBOOKS\Indian_Used_Car_Analytics\Used_Car_Analytics_Output\Fact_Used_Cars_Final.csv", "r", encoding="utf-8") as f:
    for i, line in enumerate(f, start=1):
        if line.count(",") != 21:
            print(i, line.count(","))

6 22
7 23
9 27
13 25
14 22
15 24
17 22
18 22
19 23
20 23
21 23
22 24
25 24
27 22
29 24
30 25
31 23
33 26
34 23
36 23
37 23
38 22
46 25
47 22
48 28
49 24
50 25
52 24
54 27
55 26
56 22
57 22
58 25
59 25
60 23
61 22
62 22
102 22
103 22
104 23
107 28
109 22
111 22
116 23
117 22
118 24
119 24
120 24
121 24
122 22
123 23
124 23
132 23
134 22
137 23
139 23
141 25
142 28
145 23
147 24
148 24
153 25
155 26
156 24
157 22
158 26
160 22
162 23
163 27
164 24
166 24
167 25
169 24
170 22
171 24
177 25
183 22
186 22
188 23
189 22
190 26
191 24
194 25
195 23
205 24
207 24
208 23
210 22
211 24
212 22
213 26
214 25
215 24
225 27
228 22
229 24
231 22
233 22
234 25
235 24
236 24
237 22
239 23
251 23
252 22
254 23
256 26
257 24
258 25
259 23
261 22
263 22
264 24
265 23
268 23
269 22
270 23
271 26
272 22
273 24
274 24
275 22
276 24
277 23
278 22
279 24
280 23
282 23
283 22
284 23
292 23
296 29
297 22
300 23
301 22
302 24
303 26
304 23
305 24
306 23
310 25
311 24
314 24
316 27
317 24
318 22
319 22
320 27
321 24
322 24
324 23
325 23
327 28
328 28
329 28
331 23
332 24
333 22
334 22
335 23
336 22
340 22
341 24
342 24
344 24
348 24
349 24
350 24
351 25
352 23
353 22
354 22
356 24
358 23
359 24
361 26
362 26
363 23
364 27
365 22
366 26
372 26
373 26
375 23
376 24
379 22
381 25
382 22
383 22
386 26
387 23
392 32
393 24
395 22
397 22
402 22
404 24
412 27
413 24
414 22
415 23
416 22
417 22
419 24
420 25
421 25
422 23
423 25
424 22
425 26
426 29
427 23
428 23
430 28
431 28
433 23
434 22
437 23
439 27
440 23
443 22
445 22
446 22
447 22
449 29
450 23
451 24
452 22
454 24
455 23
456 23
457 24
458 23
459 27
463 22
464 25
468 22
469 23
470 22
472 22
473 24
474 22
475 24
477 22
482 22
487 24
488 22
489 22
490 23
491 24
492 22
493 24
494 24
501 23
503 22
504 23
509 25
511 22
512 22
514 23
516 24
518 25
520 22
521 24
522 22
524 23
527 25
528 28
529 24
532 22
533 24
535 22
536 25
539 25
540 24
541 24
543 22
544 25
546 22
548 25
551 23
554 24
555 22
556 25
557 24
558 24
559 23
561 25
562 23
574 25
575 23
576 22
577 24
579 24
580 29
581 22
582 22
585 23
586 27
589 23
590 22
591 23
592 22
595 23
596 26
597 22
599 24
601 24
602 23
603 22
604 23
605 22
616 23
617 26
618 25
619 25
620 24
621 26
623 25
624 25
625 31
626 27
628 26
632 22
633 30
634 22
635 26
636 26
638 26
639 22
640 23
642 25
643 25
644 25
645 28
646 26
647 28
648 22
649 30
650 30
651 23
652 23
655 26
658 28
660 24
662 25
663 24
664 30
668 31
669 24
671 24
672 31
673 25
674 27
675 23
678 25
679 25
680 24
682 22
684 22
685 27
686 23
687 24
688 24
689 22
690 23
691 22
692 24
693 25
695 27
699 23
700 23
704 25
706 22
708 27
709 25
710 26
711 23
712 22
713 25
714 24
715 22
716 26
717 23
719 23
720 22
721 26
722 24
723 22
732 25
733 25
736 24
738 24
739 22
740 23
741 22
742 24
744 24
745 22
746 25
748 24
751 22
753 23
754 24
755 22
756 27
757 22
760 27
761 23
763 24
764 22
765 22
766 22
767 24
768 22
769 24
771 23
778 22
779 23
781 25
783 24
784 23
787 22
788 26
789 24
792 24
793 26
794 23
795 24
796 23
806 24
807 29
809 25
810 22
811 23
812 24
815 26
816 22
817 26
828 22
830 24
831 23
832 26
833 26
834 22
835 25
836 25
837 24
838 24
847 24
849 24
850 26
851 26
852 24
853 24
854 22
855 22
857 27
858 25
860 24
861 24
863 27
872 23
873 22
875 26
878 22
880 22
881 22
883 22
884 26
885 25
888 23
889 23
890 23
892 24
893 25
896 22
897 22
900 27
901 22
902 22
903 27
904 22
908 22
909 23
915 23
917 23
918 23
919 22
921 22
922 23
923 24
925 22
926 23
927 24
928 24
929 23
930 23
945 24
949 26
950 24
951 24
952 23
961 24
962 22
963 22
964 23
965 24
967 23
971 24
975 28
976 23
977 23
978 22
984 25
986 24
987 23
989 26
990 26
992 27
993 23
994 23
995 22
996 23
1002 22
1006 24
1008 24
1010 22
1014 22
1015 24
1016 23
1017 26
1019 24
1021 24
1023 22
1024 23
1025 25
1026 22
1027 24
1029 24
1030 22
1031 24
1032 23
1035 22
1037 23
1038 22
1039 23
1040 23
1041 24
1044 22
1045 23
1046 24
1047 23
1049 28
1050 22
1051 23
1052 23
1070 22
1072 23
1073 26
1076 27
1077 32
1078 22
1087 23
1088 25
1089 22
1091 22
1092 24
1093 24
1094 22
1097 24
1098 23
1100 24
1102 24
1104 22
1109 22
1113 24
1114 27
1115 24
1117 26
1118 23
1120 25
1121 24
1122 24
1123 23
1124 23
1125 24
1126 22
1127 23
1128 22
1129 24
1130 22
1131 22
1132 24
1133 22
1139 22
1143 23
1145 27
1146 27
1147 24
1150 27
1152 27
1156 24
1157 22
1159 23
1166 25
1167 22
1171 24
1173 22
1174 22
1175 22
1176 28
1177 23
1182 23
1183 27
1184 24
1186 23
1187 23
1188 26
1190 24
1191 22
1195 26
1196 28
1197 23
1198 22
1211 24
1212 23
1214 22
1215 25
1216 24
1217 22
1218 23
1220 22
1221 22
1222 22
1223 22
1225 22
1226 24
1227 27
1232 22
1233 25
1235 29
1236 24
1238 22
1242 25
1243 22
1244 27
1245 24
1247 28
1249 23
1250 22
1251 24
1253 28
1254 23
1256 22
1257 23
1258 22
1275 22
1282 22
1291 24
1293 22
1294 23
1295 23
1297 23
1299 22
1300 22
1302 23
1303 24
1304 22
1306 22
1309 28
1311 24
1312 22
1313 23
1316 24
1319 22
1324 23
1325 27
1326 26
1327 27
1328 24
1329 22
1330 24
1331 22
1332 24
1333 24
1334 23
1335 25
1336 25
1339 22
1340 22
1342 22
1345 27
1350 23
1351 23
1352 26
1353 22
1354 22
1358 22
1359 22
1360 23
1361 25
1362 22
1364 22
1365 23
1368 22
1369 23
1370 25
1372 23
1373 26
1374 24
1375 24
1377 22
1378 25
1379 23
1380 27
1381 24
1382 22
1383 24
1388 22
1390 25
1391 22
1392 26
1393 27
1394 25
1395 29
1396 22
1398 25
1400 23
1401 24
1403 26
1404 23
1405 24
1414 23
1416 22
1418 24
1419 23
1420 22
1421 24
1423 22
1427 23
1428 22
1429 23
1430 22
1434 23
1441 24
1442 24
1443 22
1444 23
1445 22
1447 24
1448 27
1449 27
1450 22
1453 23
1457 23
1459 24
1460 24
1461 23
1465 22
1471 23
1472 23
1476 23
1477 25
1478 23
1479 24
1480 26
1481 22
1482 22
1485 23
1487 22
1488 23
1490 22
1493 22
1494 24
1495 24
1496 25
1497 22
1499 24
1500 23
1502 26
1503 23
1504 24
1505 22
1507 22
1508 22
1509 22
1510 22
1511 22
1512 23
1513 26
1514 22
1516 25
1517 23
1521 24
1523 24
1524 24
1527 22
1529 23
1531 22
1532 22
1533 27
1534 25
1535 22
1536 22
1538 26
1539 22
1540 24
1541 24
1551 22
1552 26
1553 22
1554 24
1555 25
1557 25
1559 27
1560 23
1561 22
1562 27
1563 22
1564 26
1567 24
1568 24
1578 22
1579 22
1582 29
1583 26
1584 33
1585 24
1587 25
1588 23
1592 22
1596 27
1598 25
1599 22
1600 23
1602 22
1604 22
1605 23
1606 25
1608 23
1612 28
1617 22
1618 26
1620 26
1621 25
1622 22
1624 24
1625 27
1627 24
1628 27
1629 22
1633 22
1634 22
1635 24
1641 24
1643 23
1648 23
1649 22
1650 24
1651 23
1653 22
1657 26
1658 22
1660 22
1661 22
1662 23
1663 24
1664 22
1665 22
1666 23
1668 25
1672 24
1673 24
1674 26
1675 27
1676 23
1677 22
1678 24
1679 23
1680 24
1683 22
1684 24
1685 22
1686 24
1695 24
1696 23
1697 23
1699 23
1700 22
1702 23
1704 24
1705 23
1706 25
1709 24
1711 25
1715 28
1716 24
1717 22
1718 24
1719 24
1720 22
1723 24
1724 24
1728 23
1729 24
1730 27
1738 26
1739 23
1741 24
1742 26
1745 22
1746 24
1748 22
1750 24
1755 26
1756 25
1758 23
1759 25
1761 22
1763 24
1765 24
1768 25
1769 24
1771 29
1772 22
1773 23
1783 23
1784 26
1785 23
1786 25
1789 22
1790 24
1791 23
1797 25
1802 23
1803 23
1804 23
1805 22
1810 26
1811 24
1812 27
1814 24
1815 27
1816 23
1817 27
1819 22
1820 23
1821 22
1822 24
1824 24
1825 23
1827 23
1828 22
1830 23
1831 22
1832 24
1841 22
1842 25
1843 22
1845 23
1846 24
1847 24
1848 23
1850 24
1852 23
1853 27
1854 27
1855 22
1857 23
1862 23
1864 24
1865 24
1867 23
1868 23
1869 24
1870 27
1872 22
1873 22
1874 30
1875 24
1876 22
1877 25
1879 24
1881 25
1882 22
1883 22
1887 23
1888 25
1889 23
1890 26
1892 24
1893 22
1894 22
1906 30
1908 27
1910 23
1911 27
1912 25
1913 24
1914 28
1915 26
1916 24
1917 24
1918 25
1919 24
1922 22
1923 22
1924 24
1926 22
1927 26
1928 23
1929 23
1930 26
1931 24
1933 23
1935 28
1938 23
1953 25
1954 28
1955 24
1956 22
1957 25
1958 23
1959 22
1960 23
1972 25
1973 26
1975 24
1976 23
1977 24
1978 23
1980 25
1981 25
1983 23
1984 24
1986 23
1988 22
1993 22
1994 27
1995 22
1997 23
1998 22
1999 22
2000 24
2001 23
2002 26
2005 23
2006 26
2008 24
2009 27
2011 22
2012 24
2013 25
2014 23
2015 22
2016 22
2017 27
2018 24
2019 24
2020 26
2021 24
2022 26
2024 24
2026 23
2027 23
2028 23
2038 28
2039 23
2040 23
2041 23
2045 25
2046 28
2047 28
2048 27
2049 22
2050 22
2051 22
2052 22
2053 22
2054 25
2056 24
2057 22
2062 23
2065 23
2068 22
2069 23
2070 22
2071 22
2072 22
2073 25
2074 28
2076 23
2077 24
2078 28
2079 22
2080 24
2081 22
2099 26
2100 24
2101 23
2103 23
2104 23
2105 26
2108 23
2109 22
2110 23
2111 23
2113 22
2114 22
2115 23
2116 24
2117 22
2119 22
2121 24
2122 23
2124 23
2125 22
2126 24
2127 23
2129 26
2130 27
2131 22
2132 23
2133 22
2137 23
2138 22
2139 27
2141 24
2142 22
2143 27
2146 24
2147 22
2148 24
2164 22
2165 22
2167 24
2168 25
2169 22
2170 23
2174 23
2177 24
2178 24
2179 25
2181 25
2184 24
2185 22
2187 22
2189 25
2190 24
2192 25
2193 25
2200 26
2203 26
2204 22
2206 24
2209 23
2212 25
2214 24
2216 27
2217 24
2229 23
2230 23
2231 23
2232 23
2233 23
2234 26
2235 30
2236 22
2238 22
2239 23
2240 24
2251 28
2252 27
2253 26
2254 22
2256 22
2258 24
2259 26
2260 28
2261 24
2262 23
2269 24
2272 23
2273 22
2274 30
2275 23
2276 22
2277 28
2278 24
2282 22
2285 23
2286 22
2295 24
2296 23
2299 26
2303 23
2304 23
2305 24
2306 24
2309 25
2312 23
2313 25
2314 22
2315 23
2316 25
2317 22
2318 24
2319 31
2321 25
2322 23
2325 22
2326 24
2327 22
2328 23
2329 27
2330 23
2340 22
2341 23
2342 23
2343 22
2344 24
2346 22
2347 24
2349 22
2351 24
2352 22
2354 22
2355 24
2356 22
2357 27
2358 25
2359 24
2360 22
2363 25
2365 22
2366 25
2370 24
2371 23
2372 26
2373 24
2374 24
2375 22
2376 27
2377 22
2378 26
2380 24
2382 27
2383 26
2386 22
2387 23
2388 27
2390 24
2399 22
2400 27
2401 24
2405 26
2406 28
2407 24
2409 23
2410 26
2412 25
2413 28
2414 22
2417 23
2422 24
2424 25
2430 23
2432 24
2433 22
2439 24
2441 24
2443 24
2444 23
2445 24
2446 25
2450 28
2451 22
2453 24
2455 22
2456 26
2457 24
2459 27
2460 24
2461 26
2462 26
2477 24
2478 28
2480 22
2481 27
2482 23
2489 23
2490 23
2493 23
2494 26
2496 27
2498 22
2499 24
2501 22
2503 24
2505 23
2515 24
2516 23
2518 25
2520 25
2521 22
2522 26
2525 23
2526 23
2527 22
2528 24
2531 23
2532 26
2540 24
2541 22
2542 24
2543 24
2545 23
2546 29
2547 22
2548 25
2549 24
2550 26
2553 22
2554 22
2557 22
2558 24
2559 26
2560 22
2561 25
2565 22
2566 24
2567 25
2568 23
2569 23
2570 22
2572 25
2573 24
2574 22
2576 23
2577 28
2582 23
2583 23
2587 22
2589 22
2591 24
2592 22
2593 22
2594 27
2595 26
2599 23
2600 24
2602 23
2603 25
2604 22
2606 24
2607 24
2609 22
2610 25
2614 22
2615 25
2617 23
2618 25
2621 24
2622 23
2623 22
2624 24
2634 24
2635 22
2637 31
2638 25
2639 26
2641 24
2642 22
2643 26
2644 26
2645 25
2646 22
2647 24
2648 25
2651 22
2652 22
2658 23
2660 23
2661 23
2662 22
2663 24
2665 28
2666 25
2672 23
2674 23
2676 22
2677 24
2679 26
2680 24
2691 22
2693 27
2694 22
2696 25
2697 24
2698 24
2699 22
2700 24
2701 24
2702 24
2703 28
2707 27
2708 26
2709 22
2710 23
2711 25
2713 24
2714 24
2716 23
2717 29
2718 25
2719 23
2720 25
2721 26
2722 23
2723 23
2724 22
2725 23
2728 23
2730 23
2731 28
2734 22
2735 26
2736 25
2737 24
2738 26
2739 25
2741 23
2742 22
2743 25
2744 26
2748 25
2749 24
2756 22
2757 23
2758 24
2759 22
2760 22
2761 24
2763 24
2764 22
2766 22
2767 23
2769 24
2775 23
2776 23
2777 25
2778 24
2779 24
2780 23
2781 23
2782 23
2783 23
2785 22
2786 22
2787 22
2788 22
2789 23
2790 23
2792 25
2804 24
2805 28
2806 25
2807 24
2808 22
2809 24
2810 24
2812 23
2813 23
2816 22
2817 22
2818 25
2820 25
2821 26
2822 22
2823 23
2824 24
2826 23
2827 28
2830 22
2831 25
2833 24
2837 22
2838 27
2839 24
2840 22
2841 24
2842 24
2849 27
2850 24
2852 23
2853 24
2854 23
2855 24
2856 22
2857 24
2858 25
2859 22
2860 26
2863 23
2864 24
2868 24
2869 25
2870 26
2872 23
2874 24
2875 24
2876 23
2877 23
2878 23
2880 24
2883 24
2884 22
2887 22
2889 29
2890 22
2892 22
2893 23
2898 24
2899 22
2901 25
2916 25
2917 23
2918 25
2920 25
2921 23
2922 22
2925 23
2926 24
2928 24
2930 25
2931 24
2934 23
2936 22
2938 24
2939 24
2943 23
2952 26
2953 24
2955 23
2956 23
2958 22
2965 22
2966 25
2967 23
2968 23
2969 25
2970 22
2971 22
2972 22
2973 25
2974 24
2975 27
2976 24
2983 27
2984 23
2985 29
2986 26
2989 25
2990 23
2991 26
2992 22
2993 26
2994 29
2996 24
2997 22
2998 23
3005 24
3006 24
3008 23
3009 24
3010 24
3011 24
3012 24
3013 24
3014 22
3015 23
3016 24
3017 24
3020 28
3029 24
3031 23
3032 22
3033 26
3034 24
3035 24
3036 24
3037 23
3038 25
3040 26
3046 23
3047 22
3049 24
3051 22
3054 25
3055 23
3056 22
3058 24
3059 23
3061 24
3062 23
3064 23
3066 25
3067 24
3068 22
3069 27
3071 25
3073 27
3074 24
3075 23
3076 26
3077 22
3078 25
3079 22
3080 22
3082 25
3083 26
3087 24
3091 27
3092 24
3093 22
3094 22
3095 23
3096 25
3097 24
3098 25
3099 23
3100 28
3101 23
3102 22
3103 26
3104 25
3106 22
3110 23
3117 25
3118 26
3123 24
3125 25
3127 23
3128 24
3129 22
3130 28
3131 25
3132 23
3138 25
3139 27
3141 22
3142 24
3143 27
3144 25
3145 22
3146 24
3147 22
3149 22
3150 22
3153 24
3154 22
3156 23
3162 25
3163 26
3164 23
3165 24
3167 24
3168 24
3170 22
3171 22
3174 24
3175 26
3176 25
3177 28
3185 22
3187 26
3188 23
3189 23
3198 25
3199 29
3201 25
3202 24
3203 22
3204 28
3205 25
3207 27
3208 23
3210 22
3211 25
3212 23
3213 23
3215 24
3216 24
3217 25
3226 23
3227 24
3232 26
3233 26
3234 22
3236 23
3242 22
3243 22
3244 22
3248 24
3251 23
3252 23
3253 24
3254 26
3255 22
3256 23
3257 24
3258 22
3259 26
3261 26
3263 28
3265 22
3268 24
3269 24
3273 26
3276 25
3278 22
3281 23
3283 24
3284 26
3287 24
3288 24
3289 24
3290 23
3297 28
3298 23
3304 25
3305 25
3306 23
3307 25
3310 25
3311 25
3312 23
3314 24
3316 22
3318 23
3319 23
3320 25
3321 22
3322 22
3323 24
3325 25
3327 24
3328 23
3329 22
3330 25
3332 23
3333 25
3335 24
3336 26
3350 24
3351 24
3354 24
3361 23
3362 23
3365 24
3366 23
3368 22
3369 24
3371 25
3372 24
3377 28
3378 23
3382 22
3383 24
3384 23
3387 23
3388 22
3392 22
3393 22
3395 26
3396 24
3398 28
3399 23
3400 24
3401 22
3402 23
3403 22
3404 25
3405 25
3419 25
3420 28
3421 25
3423 23
3424 26
3426 24
3427 23
3428 22
3429 26
3430 22
3431 23
3432 23
3433 23
3434 24
3435 22
3437 25
3438 22
3439 24
3440 26
3441 26
3451 24
3452 24
3453 25
3454 22
3455 23
3456 26
3457 22
3460 22
3462 23
3463 25
3464 24
3465 25
3467 22
3469 23
3470 23
3471 29
3477 22
3485 28
3486 22
3488 22
3489 22
3492 24
3493 25
3496 25
3501 26
3502 22
3503 24
3504 22
3507 26
3508 25
3509 22
3510 23
3512 22
3513 25
3514 27
3525 22
3526 25
3529 24
3530 24
3532 23
3533 22
3534 24
3535 22
3539 25
3542 23
3544 25
3545 24
3547 27
3548 25
3549 24
3550 24
3552 22
3568 24
3569 22
3570 23
3572 22
3575 23
3576 22
3577 28
3578 22
3580 23
3582 25
3583 22
3584 25
3586 23
3589 23
3590 23
3592 27
3593 24
3594 22
3595 24
3597 23
3598 22
3599 24
3610 23
3611 23
3613 24
3615 25
3616 23
3618 24
3620 22
3621 25
3622 25
3623 24
3624 24
3625 22
3626 24
3627 25
3628 22
3637 22
3638 24
3639 22
3640 24
3641 26
3642 24
3643 23
3644 25
3645 22
3646 22
3647 22
3648 24
3649 26
3650 25
3653 26
3654 25
3656 25
3658 23
3659 22
3662 22
3665 26
3666 23
3667 24
3669 22
3671 22
3672 22
3677 23
3678 24
3679 22
3681 22
3686 27
3687 26
3688 23
3690 22
3693 23
3695 23
3696 24
3698 24
3699 23
3700 26
3701 26
3703 23
3704 22
3705 24
3710 24
3713 24
3718 24
3719 23
3721 22
3722 25
3723 23
3724 23
3732 23
3733 24
3735 23
3736 24
3738 23
3740 22
3741 23
3742 24
3743 23
3744 24
3745 26
3746 23
3747 23
3748 26
3749 23
3750 24
3751 22
3762 24
3763 22
3765 23
3766 24
3767 25
3768 23
3769 25
3770 22
3772 25
3773 24
3774 25
3775 23
3776 27
3777 24
3778 26
3779 24
3789 25
3790 24
3792 22
3794 25
3795 25
3798 22
3799 22
3801 25
3802 25
3803 22
3806 23
3807 22
3808 22
3814 22
3815 25
3818 24
3821 25
3822 24
3823 27
3826 23
3827 25
3831 28
3832 24
3835 25
3836 26
3837 30
3840 22
3841 23
3842 22
3845 23
3846 25
3847 26
3848 26
3849 23
3851 23
3852 22
3854 22
3856 23
3857 27
3858 22
3859 23
3865 22
3866 25
3868 23
3869 23
3875 22
3876 22
3877 22
3878 23
3879 22
3881 22
3882 27
3884 24
3885 24
3887 22
3889 28
3890 22
3891 24
3892 24
3894 22
3898 27
3901 24
3903 23
3905 25
3906 25
3907 23
3908 26
3909 23
3910 27
3911 25
3926 27
3927 22
3928 27
3929 22
3930 23
3931 25
3934 23
3935 23
3936 23
3941 24
3943 23
3944 23
3945 22
3951 23
3952 24
3953 23
3954 22
3955 29
3957 23
3958 26
3959 24
3974 24
3975 23
3976 24
3977 24
3978 24
3979 23
3980 24
3981 22
3982 25
3983 23
3985 22
3990 23
3991 24
3992 23
3993 24
3994 22
3995 23
3997 23
3998 24
3999 27
4000 26
4001 24
4002 26
4004 26
4005 22
4007 22
4008 22
4011 24
4013 23
4015 24
4017 22
4018 25
4019 23
4022 24
4025 22
4027 24
4028 24
4030 24
4031 23
4033 23
4041 31
4042 22
4043 24
4045 23
4046 23
4048 23
4049 26
4050 24
4051 25
4053 24
4055 25
4056 22
4058 22
4060 24
4074 25
4076 23
4077 22
4078 24
4080 22
4082 27
4083 22
4085 22
4087 22
4088 22
4089 24
4095 22
4096 23
4097 24
4098 23
4099 22
4104 24
4106 22
4107 22
4109 23
4114 22
4115 23
4116 22
4117 22
4118 22
4121 24
4123 23
4124 24
4125 26
4126 24
4130 24
4137 22
4138 25
4139 24
4143 23
4146 28
4147 24
4148 22
4153 22
4154 24
4156 24
4157 25
4159 22
4161 22
4162 27
4163 24
4168 22
4169 22
4171 22
4172 28
4175 25
4176 26
4179 22
4180 23
4182 26
4185 27
4186 24
4187 22
4188 25
4190 23
4191 22
4193 23
4194 22
4196 25
4203 22
4205 23
4206 22
4207 22
4208 28
4209 22
4210 22
4211 23
4213 22
4214 25
4215 24
4216 22
4219 22
4223 22
4225 28
4226 28
4227 28
4228 23
4229 25
4231 24
4233 24
4234 22
4235 23
4236 23
4237 23
4238 22
4239 22
4241 24
4248 24
4249 22
4250 25
4251 26
4252 23
4253 26
4257 23
4258 23
4259 22
4260 22
4261 23
4263 24
4264 22
4265 22
4266 25
4269 22
4270 23
4271 22
4274 24
4275 24
4279 25
4281 26
4282 24
4283 23
4284 23
4285 23
4286 22
4287 23
4290 22
4291 24
4293 27
4294 25
4295 25
4296 23
4297 25
4298 22
4299 22
4300 27
4301 24
4302 24
4303 24
4304 26
4305 25
4315 25
4317 26
4318 27
4319 24
4320 23
4322 28
4323 25
4325 26
4326 24
4327 31
4328 22
4329 24
4330 30
4336 24
4338 24
4343 31
4344 24
4345 30
4346 24
4347 25
4348 23
4349 26
4350 22
4351 23
4352 27
4354 28
4355 26
4356 23
4357 23
4358 22
4359 22
4361 28
4362 25
4363 25
4367 23
4368 22
4369 24
4372 22
4373 22
4374 23
4376 23
4377 24
4378 22
4380 23
4381 23
4394 22
4395 23
4396 23
4398 22
4399 26
4400 23
4401 24
4403 23
4405 22
4406 22
4407 23
4408 25
4411 24
4412 23
4413 27
4414 23
4415 23
4416 23
4418 23
4419 25
4420 23
4421 22
4422 22
4423 23
4424 22
4426 22
4427 24
4428 24
4429 23
4432 22
4434 22
4436 25
4437 23
4439 22
4440 23
4441 22
4442 24
4443 22
4445 24
4446 22
4447 26
4455 22
4456 25
4457 22
4459 22
4460 22
4462 23
4465 23
4466 25
4467 23
4468 24
4469 23
4470 23
4471 23
4472 24
4473 23
4477 24
4479 25
4480 25
4483 23
4485 27
4488 23
4489 24
4490 26
4491 22
4492 25
4495 24
4496 25
4497 23
4504 23
4506 22
4507 24
4510 24
4511 23
4512 24
4516 23
4517 25
4518 22
4520 24
4521 22
4525 22
4526 24
4536 22
4538 23
4539 22
4540 23
4541 25
4542 23
4543 24
4545 23
4546 23
4547 22
4548 22
4550 29
4552 23
4558 23
4559 23
4561 28
4564 22
4565 26
4566 25
4567 23
4568 24
4571 23
4573 23
4574 24
4575 22
4583 23
4584 22
4586 23
4587 22
4589 24
4590 22
4593 22
4595 24
4599 22
4600 22
4604 22
4605 22
4606 22
4607 22
4608 24
4611 22
4612 22
4614 25
4615 24
4616 24
4617 24
4618 26
4620 22
4622 24
4631 22
4634 23
4637 24
4638 25
4639 27
4640 26
4643 27
4645 22
4646 25
4647 24
4652 22
4653 24
4655 24
4657 26
4658 23
4660 24
4662 23
4663 28
4664 24
4665 23
4666 26
4667 27
4669 24
4670 23
4673 24
4675 24
4677 22
4678 24
4679 23
4683 26
4684 24
4685 23
4686 25
4687 24
4688 22
4689 25
4690 22
4691 25
4697 23
4698 25
4699 26
4700 22
4702 24
4705 26
4706 23
4707 26
4708 25
4711 24
4712 22
4713 27
4724 23
4725 24
4728 24
4729 22
4730 23
4731 23
4732 23
4736 23
4739 23
4746 23
4747 23
4752 24
4754 25
4756 24
4758 27
4761 23
4762 22
4763 27
4764 23
4766 24
4767 23
4769 26
4770 22
4776 23
4778 34
4781 25
4782 24
4786 22
4788 24
4789 23
4790 25
4791 28
4792 24
4793 22
4794 22
4795 24
4796 27
4797 25
4811 24
4813 24
4814 28
4815 23
4817 23
4819 22
4822 26
4824 27
4825 23
4826 26
4827 22
4828 22
4830 24
4833 25
4834 24
4836 24
4837 23
4838 23
4839 24
4840 22
4841 24
4842 24
4843 23
4846 26
4847 25
4848 22
4849 23
4850 25
4851 22
4852 23
4853 23
4858 22
4860 22
4861 23
4865 26
4866 24
4867 23
4868 23
4869 24
4870 23
4872 26
4874 26
4875 22
4876 24
4877 22
4878 22
4879 23

In [130]:
for col in df.select_dtypes(include="object").columns:
    count = df[col].astype(str).str.contains(r"[\r\n]", regex=True).sum()
    print(col, count)

Vehicle_Name 0
Insurance 0
Fuel_Type 0
RTO_Location 0
Ownership 0
Transmission 0
Drive_Type 0
Other_Features 0

C:\Users\sahil\AppData\Local\Temp\ipykernel_4300\1991951852.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

In [131]:
import numpy as np

print(np.isinf(df.select_dtypes(include=["float64", "int64"])).sum())

Brand_ID                   0
Model_ID                   0
Segment_ID                 0
Year_of_Manufacture        0
Vehicle_Age                0
Seats_Capacity             0
Kms_Driven                 0
Engine_Displacement        0
Power_BHP                  0
Mileage_By_Fuel_Type       0
New_Vehicle_Price_Lakh     0
Vehicle_Price_Lakh         0
Depreciation_Percentage    0
Value_For_Money_Score      0
dtype: int64

In [132]:
for col in df.select_dtypes(include="object").columns:
    bad = df[col].astype(str).str.contains("�", regex=False).sum()
    print(col, bad)

Vehicle_Name 0
Insurance 0
Fuel_Type 0
RTO_Location 0
Ownership 0
Transmission 0
Drive_Type 0
Other_Features 0

C:\Users\sahil\AppData\Local\Temp\ipykernel_4300\425011569.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

In [135]:
import csv

with open(r"C:\Users\sahil\OneDrive\Desktop\DATA ANALYTICS HANDBOOKS\Indian_Used_Car_Analytics\Used_Car_Analytics_Output\Fact_Used_Cars_Final.csv", newline="", encoding="utf-8") as f:
    reader = csv.reader(f)

    for i, row in enumerate(reader, start=1):
        if len(row) != 22:
            print(i, len(row))

In [136]:
import ast

def clean_features(x):
    if x == "No_Features":
        return "No_Features"
    try:
        return " | ".join(ast.literal_eval(x))
    except:
        return x

df["Other_Features"] = df["Other_Features"].apply(clean_features)

In [137]:
df.to_csv(
    "Fact_Used_Cars_Final.csv",
    index=False,
    encoding="utf-8",
    na_rep=""
)

In [138]:

dim_brand.to_csv(
    "Dim_Brand.csv",
    index=False,
    encoding="utf-8"
)

dim_model.to_csv(
    "Dim_Model.csv",
    index=False,
    encoding="utf-8"
)

dim_segment.to_csv(
    "Dim_Segment.csv",
    index=False,
    encoding="utf-8"
)

In [139]:
df["Other_Features"].head(20)

0                                           No_Features
1                                           No_Features
2                                           No_Features
3                                       Parking Sensors
4           Automatic Climate Control | Parking Sensors
5     Keyless Entry | Central Locking | Air Conditioner
6                                           No_Features
7     Powered Front Seats | Ventilated Seats | Heigh...
8                                       Parking Sensors
9                                         Rear AC Vents
10                                          No_Features
11    Powered Front Seats | Height Adjustable Driver...
12                       Air Purifier | Parking Sensors
13    Engine Start/Stop Button | Automatic Climate C...
14                                          No_Features
15                      Rear AC Vents | Parking Sensors
16         Height Adjustable Driver Seat | Air Purifier
17    Automatic Climate Control | Rear AC Vents | Pa...
18    Automatic Climate Control | Rear AC Vents | Pa...
19    Leather Seats | Automatic Climate Control | Ai...
Name: Other_Features, dtype: str

In [140]:
import ast

def clean_features(x):
    if x == "No_Features":
        return "No_Features"

    try:
        return " | ".join(ast.literal_eval(x))
    except:
        return x

df["Other_Features"] = df["Other_Features"].apply(clean_features)

In [142]:
df["Other_Features"].head(40)

0                                           No_Features
1                                           No_Features
2                                           No_Features
3                                       Parking Sensors
4           Automatic Climate Control | Parking Sensors
5     Keyless Entry | Central Locking | Air Conditioner
6                                           No_Features
7     Powered Front Seats | Ventilated Seats | Heigh...
8                                       Parking Sensors
9                                         Rear AC Vents
10                                          No_Features
11    Powered Front Seats | Height Adjustable Driver...
12                       Air Purifier | Parking Sensors
13    Engine Start/Stop Button | Automatic Climate C...
14                                          No_Features
15                      Rear AC Vents | Parking Sensors
16         Height Adjustable Driver Seat | Air Purifier
17    Automatic Climate Control | Rear AC Vents | Pa...
18    Automatic Climate Control | Rear AC Vents | Pa...
19    Leather Seats | Automatic Climate Control | Ai...
20    Leather Seats | Height Adjustable Driver Seat ...
21                                    Tumble Fold Seats
22                                          No_Features
23    Keyless Entry | Central Locking | Air Conditio...
24                                          No_Features
25                    Central Locking | Air Conditioner
26                                      Parking Sensors
27    Height Adjustable Driver Seat | Air Purifier |...
28    Keyless Entry | Central Locking | Air Conditio...
29    Rear AC Vents | Parking Sensors | Cooled Glovebox
30                                          No_Features
31    Keyless Entry | Central Locking | Air Conditio...
32    Height Adjustable Driver Seat | Air Purifier |...
33                             Engine Start/Stop Button
34    Height Adjustable Driver Seat | Automatic Clim...
35    Height Adjustable Driver Seat | Automatic Clim...
36            Automatic Climate Control | Rear AC Vents
37                                          No_Features
38                                          No_Features
39                                          No_Features
Name: Other_Features, dtype: str

In [143]:
print(df.shape)

(10143, 22)

In [144]:
print(df.isnull().sum())

Brand_ID                      0
Model_ID                      0
Segment_ID                    0
Vehicle_Name                  0
Year_of_Manufacture           0
Vehicle_Age                   0
Insurance                     0
Fuel_Type                     0
Seats_Capacity                0
Kms_Driven                    0
RTO_Location                  0
Ownership                     0
Engine_Displacement          81
Transmission                  0
Power_BHP                  3109
Drive_Type                    0
Mileage_By_Fuel_Type       3395
New_Vehicle_Price_Lakh        0
Vehicle_Price_Lakh            0
Depreciation_Percentage       0
Other_Features                0
Value_For_Money_Score         0
dtype: int64