In [7]:
import pandas as pd
from sqlalchemy import create_engine

In [8]:
import getpass

In [9]:
from urllib.parse import quote_plus

password = quote_plus(getpass.getpass("Enter MySQL Password: "))

In [10]:
engine = create_engine(
    f"mysql+pymysql://sahil:{password}@localhost/used_car_dwh"
)

In [11]:
master_df = pd.read_sql(
    "SELECT * FROM Fact_Used_Cars",
    engine
)

master_df.head()

,Brand_ID,Model_ID,Segment_ID,Vehicle_Name,Year_of_Manufacture,Vehicle_Age,Insurance,Fuel_Type,Seats_Capacity,Kms_Driven,...,Engine_Displacement,Transmission,Power_BHP,Drive_Type,Mileage_By_Fuel_Type,New_Vehicle_Price_Lakh,Vehicle_Price_Lakh,Depreciation_Percentage,Other_Features,Value_For_Money_Score
0,1,1705,1,Etios,2013,12,Expired,Diesel,5,150000,...,1364.0,Manual,0.0,Unknown,0.00,8.05,2.60,67.70,No_Features,4.4
1,1,1705,2,Glanza,2024,1,Expired,Petrol,5,10000,...,1197.0,Manual,0.0,Unknown,0.00,11.28,9.40,16.67,No_Features,10.0
2,2,1,3,Creta,2017,8,Comprehensive,Diesel,5,75000,...,1396.0,Manual,0.0,Unknown,0.00,11.86,6.25,47.30,No_Features,6.8
3,3,2,1,Vento,2011,14,Expired,Diesel,5,160000,...,1598.0,Manual,103.6,Unknown,20.54,10.05,1.40,86.07,Parking Sensors,4.2
4,2,3,1,Verna,2014,11,Expired,Diesel,5,120000,...,1582.0,Manual,126.3,Unknown,22.32,11.87,4.00,66.30,Automatic Climate Control | Parking Sensors,5.0

In [12]:
master_df = pd.read_sql(
    "SELECT * FROM Fact_Used_Cars",
    engine
)

In [13]:
brand_df = pd.read_sql(
    "select * from dim_brand",
    engine
)

model_df = pd.read_sql(
    "select * from dim_model",
    engine
)

segment_df = pd.read_sql(
    "select * from dim_segment",
    engine
)


segment_df.head()
model_df.head()
brand_df.head()

   Brand_ID   Car_Brand
0         1      Toyota
1         2     Hyundai
2         3  Volkswagen
3         4        Tata
4         5    Mahindra

In [14]:
model_df.head()

   Model_ID     Car_Model
0         1         1.4 E
1         2        Diesel
2         3           1.6
3         4  Xing GL Plus
4         5       XZ Plus

In [15]:
brand_df.head()

   Brand_ID   Car_Brand
0         1      Toyota
1         2     Hyundai
2         3  Volkswagen
3         4        Tata
4         5    Mahindra

In [16]:
recommendation_df = master_df.copy()

In [17]:
recommendation_df = recommendation_df.merge(
    brand_df,
    on="Brand_ID",
    how="left"
)

In [18]:
recommendation_df = recommendation_df.merge(
    model_df,
    on="Model_ID",
    how="left"
)

In [19]:
recommendation_df = recommendation_df.merge(
    segment_df,
    on="Segment_ID",
    how="left"
)

In [20]:
recommendation_df.head()

,Brand_ID,Model_ID,Segment_ID,Vehicle_Name,Year_of_Manufacture,Vehicle_Age,Insurance,Fuel_Type,Seats_Capacity,Kms_Driven,...,Drive_Type,Mileage_By_Fuel_Type,New_Vehicle_Price_Lakh,Vehicle_Price_Lakh,Depreciation_Percentage,Other_Features,Value_For_Money_Score,Car_Brand,Car_Model,Segment
0,1,1705,1,Etios,2013,12,Expired,Diesel,5,150000,...,Unknown,0.00,8.05,2.60,67.70,No_Features,4.4,Toyota,Unknown,Sedan
1,1,1705,2,Glanza,2024,1,Expired,Petrol,5,10000,...,Unknown,0.00,11.28,9.40,16.67,No_Features,10.0,Toyota,Unknown,Hatchback
2,2,1,3,Creta,2017,8,Comprehensive,Diesel,5,75000,...,Unknown,0.00,11.86,6.25,47.30,No_Features,6.8,Hyundai,1.4 E,SUV
3,3,2,1,Vento,2011,14,Expired,Diesel,5,160000,...,Unknown,20.54,10.05,1.40,86.07,Parking Sensors,4.2,Volkswagen,Diesel,Sedan
4,2,3,1,Verna,2014,11,Expired,Diesel,5,120000,...,Unknown,22.32,11.87,4.00,66.30,Automatic Climate Control | Parking Sensors,5.0,Hyundai,1.6,Sedan

In [21]:
recommendation_df = recommendation_df[
    recommendation_df["Ownership"] != "Unknown"]

In [22]:
recommendation_df.reset_index(drop=True, inplace=True)

print(f"Recommendation Dataset Shape : {recommendation_df.shape}")

recommendation_df.head()

Recommendation Dataset Shape : (10140, 25)

,Brand_ID,Model_ID,Segment_ID,Vehicle_Name,Year_of_Manufacture,Vehicle_Age,Insurance,Fuel_Type,Seats_Capacity,Kms_Driven,...,Drive_Type,Mileage_By_Fuel_Type,New_Vehicle_Price_Lakh,Vehicle_Price_Lakh,Depreciation_Percentage,Other_Features,Value_For_Money_Score,Car_Brand,Car_Model,Segment
0,1,1705,1,Etios,2013,12,Expired,Diesel,5,150000,...,Unknown,0.00,8.05,2.60,67.70,No_Features,4.4,Toyota,Unknown,Sedan
1,1,1705,2,Glanza,2024,1,Expired,Petrol,5,10000,...,Unknown,0.00,11.28,9.40,16.67,No_Features,10.0,Toyota,Unknown,Hatchback
2,2,1,3,Creta,2017,8,Comprehensive,Diesel,5,75000,...,Unknown,0.00,11.86,6.25,47.30,No_Features,6.8,Hyundai,1.4 E,SUV
3,3,2,1,Vento,2011,14,Expired,Diesel,5,160000,...,Unknown,20.54,10.05,1.40,86.07,Parking Sensors,4.2,Volkswagen,Diesel,Sedan
4,2,3,1,Verna,2014,11,Expired,Diesel,5,120000,...,Unknown,22.32,11.87,4.00,66.30,Automatic Climate Control | Parking Sensors,5.0,Hyundai,1.6,Sedan

In [23]:

def recommend_used_cars(
    budget,
    fuel_type=None,
    transmission=None,
    segment=None,
    top_n=10
):

    df = recommendation_df.copy()

    # Budget Filter
    df = df[df["Vehicle_Price_Lakh"] <= budget]

    # Optional Filters
    if fuel_type:
        df = df[df["Fuel_Type"] == fuel_type]

    if transmission:
        df = df[df["Transmission"] == transmission]

    if segment:
        df = df[df["Segment"] == segment]

    # Ranking Logic
    df = df.sort_values(
        by=[
            "Value_For_Money_Score",
            "Kms_Driven",
            "Vehicle_Age",
            "Depreciation_Percentage"
        ],
        ascending=[False, True, True, True]
    )

    # Remove duplicate vehicle names
    df = df.drop_duplicates(
        subset="Vehicle_Name",
        keep="first"
    )

    return df[
        [
            "Car_Brand",
            "Vehicle_Name",
            "Segment",
            "Fuel_Type",
            "Transmission",
            "Vehicle_Price_Lakh",
            "Vehicle_Age",
            "Kms_Driven",
            "Depreciation_Percentage",
            "Value_For_Money_Score"
        ]
    ].head(top_n)

In [24]:
recommend_used_cars(
    budget=10,
    fuel_type="Petrol",
    transmission="Manual",
    segment="Hatchback"
)

,Car_Brand,Vehicle_Name,Segment,Fuel_Type,Transmission,Vehicle_Price_Lakh,Vehicle_Age,Kms_Driven,Depreciation_Percentage,Value_For_Money_Score
7788,Maruti,Alto,Hatchback,Petrol,Manual,4.50,0,1000,4.46,10.0
9003,Tata,Tiago,Hatchback,Petrol,Manual,6.50,1,2000,5.66,10.0
293,Maruti,Wagon,Hatchback,Petrol,Manual,6.25,3,2600,19.87,10.0
1782,Hyundai,i20,Hatchback,Petrol,Manual,8.40,2,2800,9.29,10.0
6696,Maruti,Swift,Hatchback,Petrol,Manual,7.20,0,4000,2.31,10.0
9155,Maruti,S-Presso,Hatchback,Petrol,Manual,5.70,1,5000,12.17,10.0
3826,Maruti,Celerio,Hatchback,Petrol,Manual,6.50,2,5000,11.32,10.0
296,Maruti,Baleno,Hatchback,Petrol,Manual,5.75,3,5000,19.01,10.0
3175,Hyundai,Grand,Hatchback,Petrol,Manual,6.75,2,5200,13.90,10.0
428,Renault,KWID,Hatchback,Petrol,Manual,6.00,0,10000,11.11,10.0

In [25]:
# Feature Normalization for Recommendation Engine
# (Intermediate Step)

recommendation_df["Value_Score_Norm"] = (
    recommendation_df["Value_For_Money_Score"] /
    recommendation_df["Value_For_Money_Score"].max()
)

recommendation_df["Kms_Score"] = 1 - (
    recommendation_df["Kms_Driven"] /
    recommendation_df["Kms_Driven"].max()
)

recommendation_df["Age_Score"] = 1 - (
    recommendation_df["Vehicle_Age"] /
    recommendation_df["Vehicle_Age"].max()
)

recommendation_df["Depreciation_Score"] = 1 - (
    recommendation_df["Depreciation_Percentage"] /
    recommendation_df["Depreciation_Percentage"].max()
)

recommendation_df[
    [
        "Value_Score_Norm",
        "Kms_Score",
        "Age_Score",
        "Depreciation_Score"
    ]
].head()

   Value_Score_Norm  Kms_Score  Age_Score  Depreciation_Score
0              0.44   0.991935      0.700            0.321507
1              1.00   0.999462      0.975            0.832932
2              0.68   0.995968      0.800            0.525957
3              0.42   0.991398      0.650            0.137402
4              0.50   0.993548      0.725            0.335538

In [26]:
# Recommendation Score Calculation

recommendation_df["Recommendation_Score"] = (
    recommendation_df["Value_Score_Norm"] * 0.40 +
    recommendation_df["Kms_Score"] * 0.30 +
    recommendation_df["Age_Score"] * 0.20 +
    recommendation_df["Depreciation_Score"] * 0.10
)

# Round for readability
recommendation_df["Recommendation_Score"] = (
    recommendation_df["Recommendation_Score"].round(4)
)

recommendation_df[
    [
        "Vehicle_Name",
        "Value_For_Money_Score",
        "Recommendation_Score"
    ]
].sort_values(
    by="Recommendation_Score",
    ascending=False
).head(10)

     Vehicle_Name  Value_For_Money_Score  Recommendation_Score
5060      Scorpio                   10.0                1.0079
2385      Magnite                   10.0                1.0057
1913        Rover                   10.0                1.0035
2516        Sonet                   10.0                0.9997
76           Thar                   10.0                0.9997
2515          XL6                   10.0                0.9997
9865       Triber                   10.0                0.9995
7412        Venue                   10.0                0.9995
5812        Nexon                   10.0                0.9995
2001        FRONX                   10.0                0.9994

In [27]:
recommendation_df["Depreciation_Percentage"].max()

np.float64(99.78)

In [28]:
recommendation_df["Adjusted_Depreciation"] = (
    recommendation_df["Depreciation_Percentage"]
    .clip(lower=0)
)


recommendation_df["Depreciation_Score"] = (
    1 -
    (
        recommendation_df["Adjusted_Depreciation"] /
        recommendation_df["Adjusted_Depreciation"].max()
    )
)

In [29]:
recommendation_df[
    [
        "Vehicle_Name",
        "Depreciation_Percentage",
        "Adjusted_Depreciation",
        "Depreciation_Score"
    ]
].head()

,Vehicle_Name,Depreciation_Percentage,Adjusted_Depreciation,Depreciation_Score
0,Etios,67.70,67.70,0.321507
1,Glanza,16.67,16.67,0.832932
2,Creta,47.30,47.30,0.525957
3,Vento,86.07,86.07,0.137402
4,Verna,66.30,66.30,0.335538

In [30]:
recommendation_df[
    [
        "Value_Score_Norm",
        "Kms_Score",
        "Age_Score",
        "Depreciation_Score"
    ]
].describe()

       Value_Score_Norm     Kms_Score     Age_Score  Depreciation_Score
count      10140.000000  10140.000000  10140.000000        10140.000000
mean           0.728679      0.995770      0.813696            0.560385
std            0.167082      0.010947      0.115002            0.214220
min            0.400000      0.000000      0.000000            0.000000
25%            0.580000      0.994624      0.725000            0.400256
50%            0.720000      0.996237      0.825000            0.578122
75%            0.860000      0.997849      0.900000            0.728327
max            1.000000      0.999987      1.000000            1.000000

In [31]:
recommendation_df["Recommendation_Score"] = (
    recommendation_df["Value_Score_Norm"] * 0.40 +
    recommendation_df["Kms_Score"] * 0.30 +
    recommendation_df["Age_Score"] * 0.20 +
    recommendation_df["Depreciation_Score"] * 0.10
).round(4)

In [32]:
# ==========================================
# Final Recommendation Score Calculation
# ==========================================

recommendation_df["Recommendation_Score"] = (
    recommendation_df["Value_Score_Norm"] * 0.40 +
    recommendation_df["Kms_Score"] * 0.30 +
    recommendation_df["Age_Score"] * 0.20 +
    recommendation_df["Depreciation_Score"] * 0.10
).round(4)


# Top recommended vehicles overall
recommendation_df[
    [
        "Car_Brand",
        "Vehicle_Name",
        "Segment",
        "Fuel_Type",
        "Transmission",
        "Vehicle_Price_Lakh",
        "Vehicle_Age",
        "Kms_Driven",
        "Depreciation_Percentage",
        "Value_For_Money_Score",
        "Recommendation_Score"
    ]
].sort_values(
    by="Recommendation_Score",
    ascending=False
).head(10)

,Car_Brand,Vehicle_Name,Segment,Fuel_Type,Transmission,Vehicle_Price_Lakh,Vehicle_Age,Kms_Driven,Depreciation_Percentage,Value_For_Money_Score,Recommendation_Score
76,Mahindra,Thar,SUV,Diesel,Automatic,27.10,0,10000,0.11,10.0,0.9997
2516,Kia,Sonet,SUV,Petrol,Manual,11.40,0,10000,0.09,10.0,0.9997
2515,Maruti,XL6,MUV,Petrol,Manual,14.50,0,10000,0.14,10.0,0.9997
9865,Renault,Triber,MUV,Petrol,Manual,9.70,0,6000,0.41,10.0,0.9995
5812,Tata,Nexon,SUV,Petrol,Manual,11.95,0,20000,0.17,10.0,0.9995
7412,Hyundai,Venue,SUV,Petrol,Manual,11.00,0,1000,0.45,10.0,0.9995
2001,Maruti,FRONX,SUV,Petrol,Manual,10.00,0,10000,0.40,10.0,0.9994
8063,Hyundai,Creta,SUV,Diesel,Manual,15.00,0,2000,0.86,10.0,0.9991
8394,Hyundai,Alcazar,SUV,Petrol,Manual,20.00,0,20000,0.99,10.0,0.9987
7113,Toyota,Innova,MUV,Petrol,Automatic,22.96,0,10000,1.16,10.0,0.9987

In [33]:
recommendation_df[
    recommendation_df["Vehicle_Price_Lakh"] <= 10
][
    "Recommendation_Score"
].describe()

count    8046.000000
mean        0.787692
std         0.103121
min         0.542500
25%         0.702600
50%         0.781200
75%         0.871500
max         0.999500
Name: Recommendation_Score, dtype: float64

In [34]:
# Test Budget Based Recommendation

budget_df = recommendation_df[
    recommendation_df["Vehicle_Price_Lakh"] <= 10
].copy()

budget_df[
    [
        "Car_Brand",
        "Vehicle_Name",
        "Vehicle_Price_Lakh",
        "Recommendation_Score"
    ]
].sort_values(
    by="Recommendation_Score",
    ascending=False
).head(10)

     Car_Brand Vehicle_Name  Vehicle_Price_Lakh  Recommendation_Score
9865   Renault       Triber                9.70                0.9995
2001    Maruti        FRONX               10.00                0.9994
6687      Tata        Punch                9.00                0.9978
6696    Maruti        Swift                7.20                0.9976
8316   Hyundai        Exter                9.80                0.9973
9960    Maruti       Baleno                9.50                0.9960
8002    Maruti         Alto                6.05                0.9957
7788    Maruti         Alto                4.50                0.9955
2385    Nissan      Magnite                7.90                0.9949
4428    Maruti        Swift                7.00                0.9948

In [35]:
# ==========================================
# Price Advantage Feature Engineering
# ==========================================

recommendation_df["Price_Advantage"] = (
    (
        recommendation_df["New_Vehicle_Price_Lakh"] -
        recommendation_df["Vehicle_Price_Lakh"]
    )
    /
    recommendation_df["New_Vehicle_Price_Lakh"]
)


# Handle unusual cases
recommendation_df["Price_Advantage"] = (
    recommendation_df["Price_Advantage"]
    .clip(lower=0, upper=1)
)


recommendation_df[
    [
        "Car_Brand",
        "Vehicle_Name",
        "New_Vehicle_Price_Lakh",
        "Vehicle_Price_Lakh",
        "Price_Advantage"
    ]
].head()

,Car_Brand,Vehicle_Name,New_Vehicle_Price_Lakh,Vehicle_Price_Lakh,Price_Advantage
0,Toyota,Etios,8.05,2.60,0.677019
1,Toyota,Glanza,11.28,9.40,0.166667
2,Hyundai,Creta,11.86,6.25,0.473019
3,Volkswagen,Vento,10.05,1.40,0.860697
4,Hyundai,Verna,11.87,4.00,0.663016

In [36]:
# Final Recommendation Score V2

recommendation_df["Recommendation_Score"] = (
    recommendation_df["Value_Score_Norm"] * 0.35 +
    recommendation_df["Price_Advantage"] * 0.30 +
    recommendation_df["Kms_Score"] * 0.20 +
    recommendation_df["Age_Score"] * 0.15
).round(4)


recommendation_df[
    [
        "Car_Brand",
        "Vehicle_Name",
        "Vehicle_Price_Lakh",
        "Value_For_Money_Score",
        "Price_Advantage",
        "Recommendation_Score"
    ]
].sort_values(
    "Recommendation_Score",
    ascending=False
).head(10)

,Car_Brand,Vehicle_Name,Vehicle_Price_Lakh,Value_For_Money_Score,Price_Advantage,Recommendation_Score
447,Skoda,Kodiaq,0.10,7.6,0.997850,0.9152
8451,Lamborghini,Revuelto,20.00,7.6,0.980411,0.9101
4360,Mahindra,Bolero,0.16,7.2,0.986509,0.8978
1712,Kia,Carens,1.00,7.4,0.953467,0.8913
4817,Maruti,Dzire,0.70,7.6,0.916766,0.8910
5930,Hyundai,Venue,1.20,7.6,0.922680,0.8890
2989,Toyota,Fortuner,7.00,7.6,0.886987,0.8820
5144,Maruti,Dzire,0.50,7.0,0.934383,0.8753
5852,Maruti,Ertiga,2.00,7.6,0.854121,0.8721
2739,Mahindra,Scorpio,1.00,6.6,0.965730,0.8696

In [37]:
# Price Anomaly Flag


recommendation_df["Price_Anomaly_Flag"] = "Normal"

recommendation_df.loc[
    (
        (recommendation_df["Vehicle_Price_Lakh"] < 0.5)
        &
        (recommendation_df["Vehicle_Age"] <= 2)
    ),
    "Price_Anomaly_Flag"
] = "Suspicious"


recommendation_df[
    recommendation_df["Price_Anomaly_Flag"] == "Suspicious"
][
    [
        "Car_Brand",
        "Vehicle_Name",
        "Vehicle_Price_Lakh",
        "Vehicle_Age",
        "Kms_Driven",
        "Price_Anomaly_Flag"
    ]
]

,Car_Brand,Vehicle_Name,Vehicle_Price_Lakh,Vehicle_Age,Kms_Driven,Price_Anomaly_Flag
447,Skoda,Kodiaq,0.10,0,10000,Suspicious
4360,Mahindra,Bolero,0.16,0,15000,Suspicious

In [38]:
# Price Reliability Score

recommendation_df["Price_Reliability_Score"] = 1.0

recommendation_df.loc[
    recommendation_df["Price_Anomaly_Flag"] == "Suspicious",
    "Price_Reliability_Score"
] = 0.5


recommendation_df[
    [
        "Car_Brand",
        "Vehicle_Name",
        "Vehicle_Price_Lakh",
        "Price_Anomaly_Flag",
        "Price_Reliability_Score"
    ]
].head()

,Car_Brand,Vehicle_Name,Vehicle_Price_Lakh,Price_Anomaly_Flag,Price_Reliability_Score
0,Toyota,Etios,2.60,Normal,1.0
1,Toyota,Glanza,9.40,Normal,1.0
2,Hyundai,Creta,6.25,Normal,1.0
3,Volkswagen,Vento,1.40,Normal,1.0
4,Hyundai,Verna,4.00,Normal,1.0

In [39]:
recommendation_df[
    recommendation_df["Price_Anomaly_Flag"] == "Suspicious"
][
    [
        "Car_Brand",
        "Vehicle_Name",
        "Vehicle_Price_Lakh",
        "Vehicle_Age",
        "Kms_Driven",
        "Price_Anomaly_Flag",
        "Price_Reliability_Score"
    ]
]

,Car_Brand,Vehicle_Name,Vehicle_Price_Lakh,Vehicle_Age,Kms_Driven,Price_Anomaly_Flag,Price_Reliability_Score
447,Skoda,Kodiaq,0.10,0,10000,Suspicious,0.5
4360,Mahindra,Bolero,0.16,0,15000,Suspicious,0.5

In [40]:
# ==========================================
# Final Recommendation Score V3
# ==========================================

recommendation_df["Recommendation_Score"] = (
    recommendation_df["Value_Score_Norm"] * 0.40 +
    recommendation_df["Price_Advantage"] * 0.20 +
    recommendation_df["Kms_Score"] * 0.20 +
    recommendation_df["Age_Score"] * 0.15 +
    recommendation_df["Price_Reliability_Score"] * 0.05
).round(4)


# Check top recommendations
recommendation_df[
    [
        "Car_Brand",
        "Vehicle_Name",
        "Vehicle_Price_Lakh",
        "Vehicle_Age",
        "Kms_Driven",
        "Price_Advantage",
        "Price_Reliability_Score",
        "Recommendation_Score"
    ]
].sort_values(
    by="Recommendation_Score",
    ascending=False
).head(10)

,Car_Brand,Vehicle_Name,Vehicle_Price_Lakh,Vehicle_Age,Kms_Driven,Price_Advantage,Price_Reliability_Score,Recommendation_Score
8451,Lamborghini,Revuelto,20.00,0,1000,0.980411,1.0,0.9001
4817,Maruti,Dzire,0.70,0,1000,0.916766,1.0,0.8873
5930,Hyundai,Venue,1.20,1,6000,0.922680,1.0,0.8847
1712,Kia,Carens,1.00,1,3000,0.953467,1.0,0.8829
2989,Toyota,Fortuner,7.00,0,12000,0.886987,1.0,0.8813
447,Skoda,Kodiaq,0.10,0,10000,0.997850,0.5,0.8785
5852,Maruti,Ertiga,2.00,0,10000,0.854121,1.0,0.8747
5144,Maruti,Dzire,0.50,0,1000,0.934383,1.0,0.8669
8470,Mahindra,XUV,1.45,0,97000,0.909148,1.0,0.8608
4360,Mahindra,Bolero,0.16,0,15000,0.986509,0.5,0.8601

In [41]:
test_df = recommendation_df[
    recommendation_df["Vehicle_Price_Lakh"] <= 10
].copy()


test_df[
    [
        "Car_Brand",
        "Vehicle_Name",
        "Vehicle_Price_Lakh",
        "Recommendation_Score"
    ]
].sort_values(
    "Recommendation_Score",
    ascending=False
).head(10)

     Car_Brand Vehicle_Name  Vehicle_Price_Lakh  Recommendation_Score
4817    Maruti        Dzire                0.70                0.8873
5930   Hyundai        Venue                1.20                0.8847
1712       Kia       Carens                1.00                0.8829
2989    Toyota     Fortuner                7.00                0.8813
447      Skoda       Kodiaq                0.10                0.8785
5852    Maruti       Ertiga                2.00                0.8747
5144    Maruti        Dzire                0.50                0.8669
8470  Mahindra          XUV                1.45                0.8608
4360  Mahindra       Bolero                0.16                0.8601
1888  Mahindra      Scorpio                1.20                0.8562

In [42]:
# ==========================================
# Budget Range Mapping
# ==========================================
max_vehicle_price = recommendation_df["Vehicle_Price_Lakh"].max()

budget_ranges = {
    "Below 1 Lakh": (0, 1),
    "1-3 Lakh": (1, 3),
    "3-5 Lakh": (3, 5),
    "5-10 Lakh": (5, 10),
    "10-15 Lakh": (10, 15),
    "Above 15 Lakh": (15, max_vehicle_price)
}


budget_ranges

{'Below 1 Lakh': (0, 1),
 '1-3 Lakh': (1, 3),
 '3-5 Lakh': (3, 5),
 '5-10 Lakh': (5, 10),
 '10-15 Lakh': (10, 15),
 'Above 15 Lakh': (15, np.float64(750.0))}

In [43]:
# ==========================================
# Standardize User Filter Columns
# ==========================================

recommendation_df["Fuel_Type_clean"] = (
    recommendation_df["Fuel_Type"]
    .str.strip()
    .str.lower()
)

recommendation_df["Transmission_clean"] = (
    recommendation_df["Transmission"]
    .str.strip()
    .str.lower()
)

recommendation_df["Segment_clean"] = (
    recommendation_df["Segment"]
    .str.strip()
    .str.lower()
)


# ==========================================
# Test User Preference Filtering
# ==========================================

selected_budget = "5-10 Lakh"
selected_fuel = "petrol"
selected_transmission = "manual"
selected_segment = "suv"


min_price, max_price = budget_ranges[selected_budget]


filtered_df = recommendation_df[
    (recommendation_df["Vehicle_Price_Lakh"] >= min_price) &
    (recommendation_df["Vehicle_Price_Lakh"] <= max_price) &
    (recommendation_df["Fuel_Type_clean"] == selected_fuel) &
    (recommendation_df["Transmission_clean"] == selected_transmission) &
    (recommendation_df["Segment_clean"] == selected_segment)
]


filtered_df[
    [
        "Car_Brand",
        "Vehicle_Name",
        "Vehicle_Price_Lakh",
        "Fuel_Type",
        "Transmission",
        "Segment",
        "Recommendation_Score"
    ]
].sort_values(
    "Recommendation_Score",
    ascending=False
).head(10)

,Car_Brand,Vehicle_Name,Vehicle_Price_Lakh,Fuel_Type,Transmission,Segment,Recommendation_Score
5534,Toyota,Taisor,9.95,Petrol,Manual,SUV,0.8366
10112,Maruti,Brezza,8.00,Petrol,Manual,SUV,0.8351
9557,Tata,Punch,5.10,Petrol,Manual,SUV,0.8345
119,Kia,Sonet,9.50,Petrol,Manual,SUV,0.8345
3605,Hyundai,Venue,7.99,Petrol,Manual,SUV,0.8343
2644,Kia,Sonet,9.50,Petrol,Manual,SUV,0.8342
3727,Maruti,Brezza,8.20,Petrol,Manual,SUV,0.8342
3437,Hyundai,Exter,8.00,Petrol,Manual,SUV,0.8341
4330,Volkswagen,Taigun,9.90,Petrol,Manual,SUV,0.8331
9106,Mahindra,XUV300,8.00,Petrol,Manual,SUV,0.8329

In [44]:
def recommend_used_cars(
    budget_range,
    fuel_type=None,
    transmission=None,
    segment=None,
    top_n=10
):

    min_price, max_price = budget_ranges[budget_range]

    df = recommendation_df.copy()

    # Budget filter (always applied)
    result = df[
        (df["Vehicle_Price_Lakh"] >= min_price) &
        (df["Vehicle_Price_Lakh"] <= max_price)
    ]


    # Optional fuel filter
    if fuel_type:
        result = result[
            result["Fuel_Type_clean"] == fuel_type.lower()
        ]


    # Optional transmission filter
    if transmission:
        result = result[
            result["Transmission_clean"] == transmission.lower()
        ]


    # Optional segment filter
    if segment:
        result = result[
            result["Segment_clean"] == segment.lower()
        ]


    # Ranking
    result = result.sort_values(
        "Recommendation_Score",
        ascending=False
    )
    final_result = result.head(top_n).copy()

   


    return final_result[
    [
        "Car_Brand",
        "Vehicle_Name",
        "Vehicle_Price_Lakh",
        "Fuel_Type",
        "Transmission",
        "Segment",
        "Recommendation_Score"
    ]
]

In [45]:
recommendation_df.to_csv(
    "../data/processed/Recommendation_Dataset.csv",
    index=False
)

In [46]:
result = recommend_used_cars(
    budget_range="5-10 Lakh",
    fuel_type="Petrol",
    transmission="Manual",
    segment="SUV",
    top_n=10
)

print(type(result))
print(result.head())

<class 'pandas.DataFrame'>
      Car_Brand Vehicle_Name  Vehicle_Price_Lakh Fuel_Type Transmission  \
5534     Toyota       Taisor                9.95    Petrol       Manual
10112    Maruti       Brezza                8.00    Petrol       Manual
9557       Tata        Punch                5.10    Petrol       Manual
119         Kia        Sonet                9.50    Petrol       Manual
3605    Hyundai        Venue                7.99    Petrol       Manual

      Segment  Recommendation_Score
5534      SUV                0.8366
10112     SUV                0.8351
9557      SUV                0.8345
119       SUV                0.8345
3605      SUV                0.8343